callstack/react-native-testing-library

README.md, src/__tests__/render.test.js, src/helpers/getByAPI.js, src/helpers/queryBy.js, src/helpers/queryByAPI.js, src/render.js
`query` APIs corresponding to `get` APIs. For simplicity and code reuse I've decided to go with calling `get` APIs directly – as a downside we throw/catch errors twice. If this ever has a bigger perf impact we can switch the implementation.
Fixes #6 
Added unit tests
=> feat: add query API

src/helpers/errorWithStack.js, src/helpers/getByAPI.js
When moving `get` APIs outside of `render`, we needed to wrap them with a closure injecting `instance` to act on. This resulted in an anonymous callsite that wasn't properly processed by our `ErrorWithStack` helper.
|before|after|
|--|--|
|<img width="305" alt="screenshot 2018-10-07 at 16 09 27" src="https://user-images.githubusercontent.com/5106466/46582694-6fb08f00-ca4b-11e8-94f8-40dcb2211d46.png">|<img width="491" alt="screenshot 2018-10-07 at 16 09 18" src="https://user-images.githubusercontent.com/5106466/46582698-73dcac80-ca4b-11e8-94ce-4fd16ce1f845.png">|
=> fix: stack traces for get APIs

src/__tests__/__snapshots__/shallow.test.js.snap, src/__tests__/shallow.test.js
=> test: add tests for shallow rendering

README.md, src/__tests__/fireEvent.test.js, src/__tests__/waitForElement.test.js, src/index.js, src/waitForElement.js
Adds `waitForElement` API.
The idea is to await throwable callback until it stops throwing or exceeds timeout. This way we can test async invoked actions with ease.
Added tests
=> feat: add waitForElement

README.md, src/waitForElement.js, typings/__tests__/index.test.tsx, typings/index.d.ts
Add Typescript types for `waitForElement`.
=> feat Add Typescript types to waitForElement

src/__tests__/fireEvent.test.js, src/fireEvent.js
Remove bubbling events to the root element as in the most common use case we pass handler prop to the root element:
```jsx
// That's usually what we do in tests
const tree = render(<SomeElement onPress={mockedHandler} />);
// Unsupported use case
const tree = render(<TouchableOpacity onPress={mockHandler()}><Text>XD</Text></TouchableOpacity>)
```
=> fix: do not bubble event to root element

README.md, package.json, src/__tests__/__snapshots__/render.test.js.snap, src/__tests__/render.test.js, src/debug.js, src/render.js, src/shallow.js, typings/index.d.ts
Exposing `toJSON` so it's possible to snapshot/debug the fully rendered component.
By the way removed the dead code in `shallow` that was not supported (we've never actually wanted to support `shallow(Component)` as it doesn't make sense without passing props.
Fixes #33.
Added a test, which renders funny because of our mocks.
=> feat: add toJSON to render; cleanup shallow

.flowconfig, README.md, package.json, src/__mocks__/reactNativeMock.js, src/__tests__/__snapshots__/render.test.js.snap, src/__tests__/__snapshots__/shallow.test.js.snap, src/__tests__/fireEvent.test.js, src/__tests__/render.test.js, src/__tests__/shallow.test.js, src/__tests__/waitForElement.test.js, src/fireEvent.js, typings/__tests__/index.test.tsx, typings/index.d.ts, yarn.lock
This actually uncovered some bugs, like lack of `onDoublePress` (lol XD) and enabled us to have better snapshots for deep rendering.
no new tests
=> fix: use actual react-native instead of homegrown mocks

README.md, package.json, src/__tests__/__snapshots__/debug.test.js.snap, src/__tests__/debug.test.js, src/debug.js, typings/__tests__/index.test.tsx, typings/index.d.ts, yarn.lock
Adds API proposed by https://github.com/callstack/react-native-testing-library/pull/33#issuecomment-430302079.
Also component output is now highlighted:
Added tests for `debug`.
=> feat: add debug.deep and debug.shallow

.release-it.json, CONTRIBUTING.md, package.json, yarn.lock
Adding `release-it`. Fixes https://github.com/callstack/react-native-testing-library/issues/23
=> chore: add release-it for release automation

README.md, package.json
We could also make it an optional dependency and inline-require it inside debug (the only place we use it) but for now I decided to make it a regular dependency, because that's what it is, no point in making users install it directly.
green CI
=> feat: move pretty-format from peer do deps

README.md, src/__tests__/__snapshots__/debug.test.js.snap, src/__tests__/debug.test.js, src/debug.js, typings/__tests__/index.test.tsx, typings/index.d.ts
Make `debug.deep` more usable by allowing it to print arbitrary JSON (and actually any) files. This proves handy when we want to debug async component which we want to snapshot after async operations:
```jsx
const { toJSON, getByName } = render(
<Button onPress={jest.fn} text="Press me" />
);
fireEvent.press(getByName('TouchableOpacity'));
await flushMicrotasksQueue();
debug.deep(toJSON());
```
added one
=> feat: make debug.deep more usable

README.md
Updated to better compare with Enzyme capabilities while highlighting more react-native-testing-library benefits.
It is good for people to know the options (that Enzyme *can* technically be used currently for deep rendering), but also further sell the potential user on the benefits of react-native-testing-library.
This fixes #24.
I left out links to the Enzyme discussions, as it is up to the maintainers to include those and the goal is to highlight benefits while being fair.
Thanks for your consideration, and providing a great alternative to Enzyme!
See https://github.com/airbnb/enzyme/pull/1873, where I have submitted an Enzyme PR to update testing instructions for Enzyme. There I mention how Enzyme does plan an adapter to support deep rendering, but that is still open, while I also show …
=> Documentation update for The Problem section, Enzyme, benefits

package.json, src/__tests__/__snapshots__/shallow.test.js.snap, src/helpers/getByAPI.js, yarn.lock
This reverts commit d6d225d82564b5f9c3fe5e0f7da96dba2492d818.
Turned out that causes issues with testing some components, especially on RN prior to 0.57.5 (but also there). We need to update our testing suite to include all components exposed by `react-native` and implement `getNodeByName` properly.
should be green
=> Revert "fix: `getAllBy*` methods return more elements than expected (#57)"

README.md, package.json, src/__tests__/__snapshots__/shallow.test.js.snap, src/__tests__/render.test.js, src/__tests__/renderRNComponents.test.js, src/debug.js, src/fireEvent.js, src/helpers/errorWithStack.js, src/helpers/errors.js, src/helpers/getByAPI.js, yarn.lock
Migrating from RN 0.57.4 -> 0.57.5 revealed a flaw in the implementation of our helper to get nodes by name. I believe now we should have never test against `node.type` directly if it's a string, as this compares to the host component type and may result in finding more nodes than actually expected (which in RN versions prior to 0.57.5 allowed us to do `getByName('Text')` or `getByName('View')` where they didn't have `type.displayName` nor `type.name` set correctly).
This is breaking but since it fixes the behavior to correct one I'm keen on releasing this as a patch.
Migration path:
- if you can, upgrade to RN 0.57.5 to avoid some manual work
rename:
- `getByName('Text')` -> `getByName(Text)`
- `getByName('View')` -> `getByName(View)`
- `getByName('Image')` -> `getByName(Image)`
- …
=> fix(breaking): correct faulty implementation of finding by name

README.md, src/__tests__/render.test.js, src/helpers/getByAPI.js, src/helpers/queryByAPI.js, typings/__tests__/index.test.tsx, typings/index.d.ts
Adds new `getByType`, `getAllByType` render helper and `query*` equivalents to find components by type only. This is going to be the method where we'll point `getByName` when deprecation.
Included.
=> feat: add getByType helper

README.md, src/__tests__/__snapshots__/render.test.js.snap, src/__tests__/debug.test.js, src/__tests__/render.test.js, src/debug.js, src/helpers/debugDeep.js, src/helpers/debugShallow.js, src/helpers/format.js, src/render.js, typings/__tests__/index.test.tsx, typings/index.d.ts
Adds `debug` and `debug.shallow` to `render` helpers to render. It's way more convenient than importing `debug` from the library, and feeding the component/json output to it. Plus it aligns well with [`react-testing-library`'s debug](https://github.com/kentcdodds/react-testing-library/#debug). Also improved the custom message by adding it to the top for easier discovery. Added docs say it all:
```jsx
const { debug } = render(<Component />);
debug('optional message');
```
logs optional message and colored JSX:
```jsx
optional message
<TouchableOpacity
activeOpacity={0.2}
onPress={[Function bound fn]}
>
<Text>Press me</Text>
</TouchableOpacity>
```
Included, some adjusted.
=> feat: add debug to render helpers for easier console debugging

README.md, src/helpers/errors.js, src/helpers/getByAPI.js, src/helpers/queryByAPI.js
Deprecating `getByName`, `getAllByName` and related `query*` APIs. They proved promoting fragile tests and should be avoided.
This is only temporary so I've decided to just leave the warnings so we can also see them in our tests. If it starts to annoy maintainers, we'll need to mock the `logDeprecationWarning` helper and snapshot the output.
=> feat: deprecate getByName helpers

docs/api.md
`getByType` was added in v1.4, but since we're not versioning our docs, it's worth to not when it was added.
=> docs: add note about new APIs in v1.4

docs/api.md, src/__tests__/__snapshots__/shallow.test.js.snap, src/__tests__/shallow.test.js, src/debug.js, src/helpers/debugShallow.js, src/render.js, src/shallow.js
Existential type (`*`) is long deprecated, let's just use `any` for now.
Added some more Flow typings to `shallow.test.js` that were failing because of existential type.
=> fix: remove deprecated existential Flow type and use any for now

README.md
As discussed in https://github.com/callstack/react-native-testing-library/issues/96, I found that I could get RNTL working with Jest but not with Mocha. I haven't _confirmed_ it doesn't work with Mocha, but I think it would be helpful for users (like me) who don't have a strong preference which runner to use, to know that Jest could be a good first choice.
No code changes, just README
=> Clarify RNTL is tested to work with Jest

docs/API.md, src/__tests__/__snapshots__/render.test.js.snap, src/__tests__/render.test.js, src/helpers/getByAPI.js, src/helpers/queryByAPI.js, typings/__tests__/index.test.tsx, typings/index.d.ts
There is a helper that exists in `react-testing-library` to query inputs by their `placeholder`. This PR adds that support.
You **could** achieve this by querying for a `placeholder` prop, or querying for react native `TextInput`s manually and then checking their props, but it felt cleaner to have this contained in the testing library itself. It will also allow you to bypass any other instances that may have a `placeholder` prop that aren't `TextInput`s.
If we don't want to expand the surface of the library further, I completely understand that and am fine with this being closed. Just seems like it may be useful and save some time for several scenarios =)
+ Render a `TextInput` with a `placeholder` prop
+ Query the test instance via `getByPlaceholder` for the input
+ Verify the test …
=> Add getByPlaceholder query functionality

docs/API.md
I personally encountered some confusion with the `fireEvent` api (via #100), and didn't immediately realize events did not require an aliased to be fired.
This PR adds some documentation to help make that api as clear as possible for new users.
=> Add more details to the fireEvent api documentation

package.json, yarn.lock
=> chore: bump jest to v24.1

docs/API.md, flow-typed/npm/react-test-renderer_v16.x.x.js, package.json, src/__tests__/act.test.js, src/act.js, src/fireEvent.js, src/index.js, src/render.js, typings/__tests__/index.test.tsx, typings/index.d.ts, yarn.lock
Make testing hooks easy.
Unit tests are included in PR.
Fixes #111
=> feature: better support for hooks

.flowconfig, babel.config.js, package.json, yarn.lock
We have a security alert around `merge` so I bumped that, also upgraded to latest metro preset version (it's still Node 8 compatible), updated RN to 0.58.6
Removed the version check for Flow as we always use local version anyway.
Check build directory
=> chore: update metro and merge deps

README.md
Update README documentation links to reference website.
Click the links found at the bottom of the README.
=> docs: Update links

docs/API.md
I removed misleading recommendation to render components with `shallow` in snapshot tests as a result of the conversation in Issue #127.
Review text in API.md
=> docs: Remove misleading recommendation to use shallow in snapshot tests

docs/API.md, src/__tests__/render.test.js, src/helpers/getByAPI.js
Given a component that renders text by composing together literal text with an inline expression for a dynamic variable, React Native will render this as a `<Text>` element with multiple children. For example:
```js
const BananaCounter = ({ numBananas }) => (
<Text>There are {numBananas} bananas in the bunch</Text>
);
const { toJSON, debug } = render(<BananaCounter numBananas={3} />);
debug();
/*
<Text>
There are
3
bananas in the bunch
</Text>
*/
expect(toJSON()).toMatchInlineSnapshot(`
<Text>
There are 
3
bananas in the bunch
</Text>
`);
```
This makes sense, as the component is a:
- literal string
- a dynamic evaluation
- literal string
Unfortunately, this means that writing a test that finds an element based on that dynamic evaluation fails when using `getByText`.
```js
const { …
```
=> Allow for text to match children who are composed as array

src/helpers/getByAPI.js
Check for undefined/null values, in `getByText` nodes.
Fixes #135 
Passing tests on repro repository https://github.com/wKovacs64/rntl-161-repro.
Have no idea how to create a unit test, to test this behavior.
cc @thymikee @wKovacs64
=> fix: check for undefined/null children

docs/API.md, src/__tests__/act.test.js, src/render.js
Currently `render` and `fireEvent` are wrapped in `act` to support hooks. This pull request wraps the update call in `act` to support testing component updates (e.g. prop changes).
* I have added a test for update in `__tests__/act.test.js`.
* A useEffect hook should run again on `update` calls (if the hook dependency array is satisfied).
=> Add act to update call to support hooks

docs/API.md
Some people find it useful to search for specific terms when browsing the docs.
Specifying the concrete utility of the `update` method makes the doc more useful :)
=> docs: provide example for componentDidMount

docs/API.md, src/__tests__/render.test.js, src/render.js, typings/__tests__/index.test.tsx, typings/index.d.ts
Users of `react-testing-library` use `rerender` wording instead of `update`. Let's make it easier for them by aliasing it.
See: https://testing-library.com/docs/react-testing-library/api#rerender
Added cases for JS tests and TS typings
=> feat: add `rerender` as an alias for `update`

README.md, docs/API.md, docs/GettingStarted.md
Since the original `react-testing-library` doesn't have `shallow` API, we want to be compatible with it and remove it in `2.0` release. For, now just remove it from the documentation.
=> Docs: Remove shallow API from docs

README.md
The readme's "Rally Health" link is a 404.  It appears to attempt to link to a careers page.  I skillfully sniffed out a suitable careers page by scrolling down on the 404 page and clicking "careers".
0. Scroll to the bottom of `README.md`;
0. Middle click on "Rally Health";
0. Bask (optional).
=> Fixed a 404 in `README.md`.

website/static/css/custom.css
Since `primaryColor` is dark, links are indistinguishable from regular text. We need to override it for all links in global `css`.
(Docusaurus issue: https://github.com/facebook/Docusaurus/issues/1168)
=> fix: change link colors

docs/API.md, src/__tests__/render.test.js, src/render.js, typings/index.d.ts
Adds `wrapper` option to render function to allow users to specify a WrapperComponent that will be used by render, update, and rerender.
Resolves #172
Added tests. Tested `rerender` and not `update` since it is an alias. Could test both or just `update` instead...
1. I was basing this off of `native-testing-library` https://github.com/testing-library/native-testing-library/blob/master/src/index.js#L16-L23. They are wrapping all tests in `AppContainer` which I'm not sure why. Maybe to pick up yellow box errors?
2. I thought their implementation was also hiding the WrappedComponent from errors and debug/snapshot outputs. Pretty sure they aren't doing any such thing and it's just that the Providers I was rendering don't actually have any user facing output. (Still getting used to non-enzyme …
=> feat: Add `wrapper` option to render

src/__tests__/fireEvent.test.js, src/fireEvent.js
The error callsites for special handlers (`press`, `changeText`, `scroll`) in `fireEvent` were wrong. We can fix that by passing the correct callsite along so that it's available.
Before
After
=> fix: display correct error frame when `fireEvent` fails

docs/Queries.md, src/__tests__/__snapshots__/render.test.js.snap, src/__tests__/render.test.js, src/helpers/getByAPI.js, src/helpers/queryByAPI.js, typings/__tests__/index.test.tsx, typings/index.d.ts
Implement `ByDisplayValue` queries so we can assert on `TextInput` values.
Added tests
=> feat: implement ByDisplayValue queries

README.md
Typo fixed in Installation part of Readme
=> chore: Typo fixed in readme

src/__tests__/__snapshots__/render.test.js.snap, src/__tests__/render.test.js, src/helpers/getByAPI.js, src/helpers/queryByAPI.js, typings/__tests__/index.test.tsx, typings/index.d.ts
Implements `getAllByTestId` and `queryAllByTestId` queries.
Closes #186, Resolves #161
I wrote a test and added two `<Text>` components to the component under test as a simple, contrived example. If you want me to think of a more realistic use case or you want to suggest one I'd be happy to try that. Maybe buttons in a loop or a child component or something. But I don't want to add complexity to the example component.
=>  feat: add getAllByTestId and queryAllByTestId queries

docs/API.md, src/__tests__/fireEvent.test.js, src/fireEvent.js, typings/__tests__/index.test.tsx, typings/index.d.ts
Allow user to pass multiple parameters into the event handler function.
```ts
fireEvent(getByA11yLabel('some-button'), 'customPress', '1st param', '2nd param');
```
Added UT, and Typescript tests.
=> feat: support multiple params in event handlers

.flowconfig, package.json, src/__tests__/__snapshots__/debug.test.js.snap, src/__tests__/__snapshots__/render.test.js.snap, src/__tests__/__snapshots__/shallow.test.js.snap, src/__tests__/debug.test.js, src/__tests__/render.test.js, src/helpers/errors.js, yarn.lock
Upgraded React Native dev dependency to 0.60 and all other deps along the way. 
Green CI
=> chore: bump React Native to 0.60

src/helpers/a11yAPI.js, typings/index.d.ts
Fix for `getAllByA11y*` types.
Types were failing for following use case:
```ts
fireEvent.press(getAllByA11yLabel('label')[0]);
```
=> fix: correct typings for a11y queries

.npmignore
I noticed that `src` folder was published along with `build`, and `website` was all included in the release on npm.
By removing these two folders, we moved from:
- 📦A tarball of 162 KB to 34 KB **(-79%)**.
- 🗂️An unzipped folder of 295 KB to 135 KB **(-54%)**.
Ran our tests with modified `react-native-testing-library`.
=> Exclude src and website folder from npm release

docs/API.md
When testing scroll on a flatlist, I was getting the error : `TypeError: cannot read property 'height' of undefined`
```
export class InfiniteScrollFlatList<Item> extends PureComponent<Props<Item>> {
private handleLoadMore = () => {
if (!this.props.isLoadingMore && this.props.nextPage) {
this.props.fetchMore({ page: this.props.nextPage });
}
};
private renderListFooter = () => {
if (this.props.isLoadingMore) return <Loader />;
return null;
};
public render() {
return (
<FlatList
{...this.props}
onEndReachedThreshold={0.2}
onEndReached={this.handleLoadMore}
ListFooterComponent={this.renderListFooter}
/>
);
}
}
```
=> docs: add fireEvent.scroll example for FlatList

docs/API.md, src/__tests__/cleanup.test.js, src/cleanup.js, src/index.js, src/render.js, typings/index.d.ts
https://github.com/callstack/react-native-testing-library/issues/234#issuecomment-555725623
Every `render` call stores its `unmount` function in a global `Set` called `cleanup.queue`. This is how RTL does it (except it doesn't expose the queue). I exposed the queue on `cleanup` because it was easiest. You can adjust that in a follow-up commit if you want.
The `cleanup` function is **never** called automatically in this PR.
https://github.com/callstack/react-native-testing-library/commit/f08f132a202eaaf88019dab7c40c855105afd2af
=> feat: add "cleanup" function

.eslintrc, docs/API.md, package.json, src/__tests__/a11yAPI.test.js, src/__tests__/debug.test.js, src/__tests__/render.test.js, src/__tests__/waitForElement.test.js, src/helpers/a11yAPI.js, src/helpers/getByAPI.js, src/helpers/queryByAPI.js, src/waitForElement.js, yarn.lock
Bumping Flow to the latest supported by RN 0.61. Also
- removed deprecated usage of `*` operator
- bumped ESLint and `@callstack` preset
- disabled `react/no-multi-comp` rule
- removed unused `chalk`
- bumped TS to 3.7
🍏CI
=> chore: bump Flow and ESLint preset

src/__tests__/__snapshots__/render.test.js.snap, src/__tests__/render.test.js, src/helpers/getByAPI.js
When the number `0` is integrated into a component via a variable, `getByText('0')` does not find any `Text` instance.
**Example.jsx**:
```jsx
const test = 0;
...
<Text>{test}</Text>
```
**Example.test.jsx**:
```jsx
const testInstance = render(<Example/>);
getByText('0'); // throws whereas it should not, as there is a 0 in a text component
```
A test has been added in render.test.js
=> fix: (getByText) more robust null/undefined check for text children

docs/Queries.md
Fixes https://github.com/callstack/react-native-testing-library/issues/233
=> docs: clarify how `queryBy` behaves

src/__tests__/a11yAPI.test.js, src/helpers/a11yAPI.js, src/types.flow.js, typings/__tests__/index.test.tsx, typings/index.d.ts
Introduction of `byA11yState` matcher and improvement of types.
Added UT and Typescript tests
=> feat: byA11yState matcher

src/helpers/errors.js, src/helpers/getByAPI.js, src/helpers/queryByAPI.js, typings/index.d.ts
Re-alias every deprecated method with `UNSAFE_` prefix and add a warning.
For now, I decided not to include any warnings for re-aliased functions (but we should definitely include some messages after we delete original methods)
cc @thymikee 
Everything is logged correctly.
https://app.circleci.com/pipelines/github/callstack/react-native-testing-library/758/workflows/e3d488a4-dd12-4e68-9bae-7cbc7951bd96/jobs/2865/parallel-runs/0/steps/0-102
=> imp: Re-alias deprecated matchers and warn

src/__tests__/a11yAPI.test.js, src/helpers/a11yAPI.js, src/types.flow.js, typings/__tests__/index.test.tsx, typings/index.d.ts
Implement `byA11yValue` matcher.
`accessibilityValue` is available in React Native 0.62.x.
UT and Typescript tests included
=> feat: byA11yValue matcher

src/helpers/debugShallow.js, src/shallow.js
Deprecate `shallow` function and prepare to remove it from exports for the next release.
Nice and clean warning message.
=> imp: Deprecate shallow

docs/Queries.md
- Add docs for `a11yState` and `a11yValue`.
- Prepare docs for 2.x release
=> docs: Add new a11y matchers and prepare for 2.x

README.md
Seems like Gatekeeper is not more (https://greenkeeper.io/) and their badge doesn't work anymore. They recommend migrating to Snyk, but I don't have permissions so this is something that we need to discuss offline.
=> fix: remove gatekeeper badge

docs/GettingStarted.md, src/__tests__/questionsBoard.test.js
The example we had was based on some 3rd party code without source. Let's change to so it's easier for people to give the library a try. I've put the implementation into our test suite.
Added a new test for QuestionBoard from the docs.
=> chore: update GettingStarted example with something you can run

src/__tests__/queryByApi.test.js, src/helpers/getByAPI.js
This fixes the problem as described in https://github.com/testing-library/native-testing-library/issues/121. In short, `getByText` and `queryByText` would not find a match when the `<Text>` component has a nested component inside of it. This was caused by calling `toString()` on all components it found, meaning something like an `<Image>` would result in `[object Object]`.
A workaround would be to use a regex match for your text instead so you could decide that that is better than this proposed fix, although I would recommend detailing that somewhere as this isn't easy to debug.
I've provided a few unit tests and made sure the code supports a scenario in an existing unit test. That being said, I'm not 100% confident that this change will behave as intended for all scenarios (i.e. we now …
=> Fixed an issue where xByText would call toString() on objects and only match on `[object Object]`

docs/API.md, docs/Queries.md, src/__tests__/act.test.js, src/__tests__/fireEvent.test.js, src/__tests__/render.test.js, src/__tests__/shallow.test.js, src/__tests__/waitForElement.test.js
Fixes #283 
All examples using `getByTestID` have been replaced with alternatives, such as `getByText`,  or `getByPlaceholder`.
Tests that employed this have also been changed to use the alternatives
=> Remove use of `getByTestID` in documentation

src/__tests__/queryByApi.test.js, src/helpers/getByAPI.js, yarn.lock
Support `*ByText` to match text for nested `Text` components.
Closes #275
- Nest node into `Text`, eg `<Text/>RN Testing <Text/>Library</Text></Text>`
- Check the existence of 'RN Testing Library' with `getAllByText`
=> feat: query nested text nodes

website/docs/Queries.md
Based on [this issue](https://github.com/callstack/react-native-testing-library/issues/303) I've updated the docs for ByTestId queries.
Closes #303
Not applicable.
=> Added usage notes for ByTestId queries

README.md, src/__tests__/within.test.js, src/index.js, src/within.js, typings/__tests__/index.test.tsx, typings/index.d.ts, website/docs/API.md
This commit implements #297. New `within` operator, inspired by RTL operator of the same name exposes queries bound to given element. 
Available queries are the same as those from `render` (so getBy, queryBy, incl. A11y). Additional `render` specific operations like `update`, `unmount`, `debug`, `toJSON` are NOT included.
Added unit test for within operator as well as typescript type definitions tests.
=> `within` operator for bound queries

.eslintrc, package.json, src/__tests__/a11yAPI.test.js, src/__tests__/debug.test.js, src/__tests__/questionsBoard.test.js, src/__tests__/render.test.js, src/__tests__/waitForElement.test.js, src/cleanup.js, src/flushMicrotasksQueue.js, src/helpers/a11yAPI.js, src/helpers/findByAPI.js, src/helpers/getByAPI.js, src/helpers/makeQuery.js, src/render.js, src/waitForElement.js, yarn.lock
=> chore: bump eslint config to latest

src/__tests__/getByApi.test.js, src/helpers/findByAPI.js, src/helpers/getByAPI.js, website/docs/Queries.md
Existing version of `getByTestId` had a bug (#270) as it returned also non-native elements. This was in contract with `getAllByTestId` which returned only native elements.
Added tests checking `getByTestId` behavior.
=> fix(breaking): `getByTestId` should work only for native elements

README.md, src/__tests__/findByApi.test.js, website/docs/Migration20.md, website/docs/MigrationTo20.md, website/sidebars.js
(Nearly) empty migration doc for ver. 2.0. It contains only `getByTestId` notes that I have already written for respective bug.
=> (Nearly) Empty migration doc for ver. 2.0

babel.config.js, package.json, src/__tests__/__snapshots__/render.test.js.snap, website/docs/Migration20.md, yarn.lock
No need to compile the library with Metro, which intends to be run on JSC/Hermes. RNTL is consumed by Node.js. Using Node 10 and deferring this to v2. We can also make it into v1 with Node 8.3, but I don't care too much
Unsure
=> chore(breaking): compile project to Node 10 using @babel/preset-env

typings/__tests__/index.test.tsx
I have compacted our TS typedefs tests, so that queries with same return type are grouped together as an array, which makes the code more compact and easier to spot missing/wrong tests.
=> maintenance: cleanup TS typedefs tests

README.md, src/flushMicroTasks.js, src/flushMicrotasksQueue.js, src/helpers/errors.js, src/index.js, src/pure.js, typings/index.d.ts, website/docs/API.md, website/docs/Migration20.md
Making `flushMicrotasksQueue` deprecated in favor of `findBy` and `waitFor`.
Closes #339
=> chore(breaking): deprecate flushMicrotasksQueue

website/docs/MigrationV2.md
I ran the documentation through the http://www.hemingwayapp.com to make sure it's as easy to read as feasible. Also adjusted a few things.
=> docs: cleanup migration doc

src/waitFor.js, website/docs/API.md, website/docs/GettingStarted.md, website/docs/MigrationV2.md, website/docs/Queries.md
Wrap `waitFor` in (async) act to support async queries without explicit `act` call. Otherwise there was a problem when async state changes caused by e.g. async `useEffect` uses (fetching data, ...) generated dreded `act` warnings in the console during test runs.
Closes #343
=> feat: wrap `waitFor` in (async) act to support async queries without explicit `act` call

.github/ISSUE_TEMPLATE/bug_report.md
Current `ISSUE_TEMPLATE` file can be improved to me more exhaustive & can ask detailed question that can help report better bug reporting.
=> Update issue template to be more exhaustive

examples/reactnavigation/src/__tests__/AppNavigator.test.js, website/docs/ReactNavigation.md
This change updates the documentation around React Navigation integration to use the find* queries instead of get* queries.
It solves the tests displaying errors regarding ForwardRef(NavigationContainer).
Only a documentation change.
=> docs: update React Navigation tests to use find queries

.npmignore, package.json
We publish way more than necessary because we forgot to update npmignore. 
With this change publish size goes down from 170kB -> 20.8 kB
I think I included everything necessary for publishing, but please double check after me.
`npm pack`:
<details>
```
npm notice 📦  react-native-testing-library@2.0.0
npm notice === Tarball Contents ===
npm notice 1.1kB  LICENSE
npm notice 6.7kB  build/helpers/a11yAPI.js.flow
npm notice 146B   build/act.js.flow
npm notice 255B   build/cleanup.js.flow
npm notice 318B   build/helpers/debugDeep.js.flow
npm notice 458B   build/helpers/debugShallow.js.flow
npm notice 1.4kB  build/helpers/errors.js.flow
npm notice 2.6kB  build/helpers/findByAPI.js.flow
npm notice 1.9kB  build/fireEvent.js.flow
npm notice 372B   build/flushMicroTasks.js.flow
npm notice 255B …
```
=> chore: use files entry instead of npmignore; reduce publish size

README.md, src/__tests__/waitForElementToBeRemoved.test.js, src/pure.js, src/waitForElementToBeRemoved.js, typings/__tests__/index.test.tsx, typings/index.d.ts, website/docs/API.md
`waitForElementToBeRemoved` implementation with tests & typescript types.
Resolves #375 
Added tests based on `waitFor` & veryfing `getBy`, `getAllBy`, `queryBy` & `queryAllBy` queries.
=> feature: wait for element to be removed

website/docusaurus.config.js
The website is not correctly linking to github. It links to https://callstack.github.io/callstack/react-native-testing-library instead
=> Fix link to GitHub from footer

website/docs/API.md
Replace react-testing-library imports with react-native-testing-library in API examples. 
Nothing to test
=> Replace imports

src/__tests__/auto-cleanup-skip.test.js, src/__tests__/auto-cleanup.js, src/__tests__/auto-cleanup.test.js, src/__tests__/waitFor.test.js, src/__tests__/waitForElementToBeRemoved.test.js, src/flushMicroTasks.js
Fixes #391 
Added regression tests.
=> fix: modern jest timers

typings/index.d.ts
Fixes https://github.com/callstack/react-native-testing-library/issues/413
Adding a `@ts-ignore` for a prop that was [removed](https://reactnative.dev/blog/2020/03/26/version-0.62#breaking-changes) in RN0.62
=> Add a @ts-ignore for AccessibilityStates to support types for RN0.62+

website/docs/MigrationV7.md
=> docs: add migration to v7 guide

src/__tests__/within.test.js, src/pure.js, src/within.js, typings/__tests__/index.test.tsx, typings/index.d.ts, website/docs/API.md, website/docs/MigrationV7.md
TL/RN v6 has provided `getQueriesForElement` for scoping queries to given element & it's children. RNTL v2 had a similar `within` function. Both of these were modeled on similar RTLs helper. In RTL both names are available (as alias) to provide the same function. 
I've added `getQueriesForElement` as an alias to `within`.
Resolves #457 
* tests for checking that functions are the same
* typescript type checks
=> feat: add `getQueriesForElement` alias to `within`

.github/ISSUE_TEMPLATE/bug_report.md, CONTRIBUTING.md, README.md, pure.js, src/helpers/errors.js, website/docs/API.md, website/docs/GettingStarted.md, website/docs/Queries.md, website/docs/ReactNavigation.md, website/docs/ReduxIntegration.md
Updated package name used in docs.
N/A
=> fix: update package name in docs

src/__tests__/fireEvent.test.js, src/fireEvent.js, website/docs/API.md, website/docs/MigrationV7.md
Prevent calling event handlers for disabled components.
Fixes #28 
Added tests for `TouchableOpacity` and `Pressable` in two configuration: lone element (expected throw no handler found) and nested elements: inner disabled, outer handling event.
=> feat: prevent events on disabled elements

README.md, examples/reactnavigation/package.json, examples/reactnavigation/src/__tests__/AppNavigator.test.js, examples/redux/components/AddTodo.test.js, examples/redux/components/TodoList.test.js, examples/redux/package.json, package.json, website/docusaurus.config.js
Rename the library 🚀 .
Left a few references to `react-native-testing-library` because we keep the documentation and repo URLs untouched. Ref-links for traffic also stay unchanged.
Release a release candidate once this is merged.
=> chore(breaking): rename to @testing-library/react-native

src/__tests__/fireEvent.test.js, src/fireEvent.js
Fixes #469 
RNTL has a check that throws error when event handler missing. This is intended to inform developer that there is a mismatch between test assertions and components under test. This PR fixes a cases when this check throws error while component has a disabled event handler.
* updated tests for present & disabled handler not to throw
* we already have test for missing handler (not disabled), and for success cases
=> fix: fire event should not throw for disabled handler

src/__tests__/queryByApi.test.js, src/helpers/getByAPI.js
When using `getByText()` on a component using nested `Text`s, it should match the closest one.
```jsx
<Text id={1}>
<Text id={2}>My text</Text>
</Text>
```
I've found this bug when trying to upgrade from `@5.X` to `@7.X`, this breaks one of my tests where an `onPress` handler is attached to the lower Text, and since `getByText` returns  its parent, using `fireEvent.press(getByText('My text'))` doesn't work.
The added tests should show the covered case. I added an another test to be sure I would not introduce a regression.
=> fix: Return closest Text matching a query

website/docs/MigrationV7.md, website/docs/Queries.md, website/docusaurus.config.js
Followup to #509 
This time I ran `docusuarus publish` locally to resolve all issues, hope it works now 🤞
=> chore(docs): followup fixes for docusaurs alpha.61

.circleci/config.yml
Docusaurus performs some checks when building, it's worth to run `build` before it reaches master and catch the errors early.
CI
=> chore: test website build on CI

website/docs/MigrationV7.md
Fixes https://github.com/callstack/react-native-testing-library/issues/513 by mentioning removal of `baseElement` in the migration guide. We _could_ add it to the library, but there's little to no push on that feature. Happy to introduce it later, if requested.
None
=> fix: add note about baseElement removed from render

src/__tests__/fireEvent.test.js, src/fireEvent.js
Prevent `fireEvent` from calling event handlers on `TextInput` when `editable` prop is `false`.
Fixes #476 
**Implementation:**
Added `isTextInputComponent()` helper function to check if element is a `TextInput` and if it is then check `editable` prop instead of `onStartShouldSetResponder`
Added tests for standalone TextInput and TextInput with a nested Text component.
=> feat: support 'editable' prop on TextInput

website/docs/API.md
Update documentation to explicitly state that one should not await the return or resolution of a `waitFor` call when relying upon timer mocks.
=> Clarify waitFor documentation in regards to timer mocks

website/docs/API.md
Update documentation to explicitly state that one should not await the return or resolution of a `waitFor` call when relying upon timer mocks.
Update additional documentation overlooked in #538.
=> Clarify additional waitFor documentation

website/docs/MigrationV2.md, website/docs/Queries.md
This PR is inspired by the discussion happening here https://github.com/wix/Detox/issues/2313.
There's no need for us to recommend users whether they should avoid `ByTestId` queries or not. In fact, I noticed that developers tend to take our recommendations seriously and, maybe due to lack of better ideas, use `accessibilityHint` the same way as `testID`, which is even worse for the users, as they get some rubbish developer metadata instead of actual feedback. 
For reference, here's Apple guideline on how and when `accessibilityHint` should be used: https://developer.apple.com/documentation/objectivec/nsobject/1615093-accessibilityhint. I've adjusted our example accordingly, so it doesn't spread misleading information.
Docs
=> docs: adjust ByTestId misleading warnings; add guidelines about accessibilityHint

src/__tests__/a11yAPI.test.js, src/__tests__/render.test.js, src/helpers/errors.js, src/helpers/getByAPI.js, src/helpers/makeQuery.js
Implements https://github.com/callstack/react-native-testing-library/issues/549
Add the value that was expected in error message for the following methods:
- `getByText('bla')` => No instances found with text 'bla'
- `getByPlaceholderText('bla')` => No instances found with placeholder text 'bla'
- `getByDisplayValue('bla')` => No instances found with display value 'bla'
- `getByA11yLabel('bla')` => No instances found with accessibilityLabel 'bla' 
- `getByA11yHint('bla')` => No instances found with accessibilityHint 'bla' 
- `getByA11yRole('bla')` => No instances found with accessibilityRole 'bla' 
- `getByA11yStates('bla')` => No instances found with accessibilityStates 'bla' 
- `getByA11yState({ disabled: true})` => No instances found with accessibilityState '{"disabled":true}' 
- …
=> feat: add the value expected in getBy error messages 

website/docs/HowShouldIQuery.md, website/sidebars.js
This PR ports the  'How Should I Query?' guide from this page: https://www.native-testing-library.com/docs/guide-queries.
The 'Manual Queries' section is not included since the `findAll` method is not supported by the current version of the library.
Fixes #512 
Also these methods were not documented in the original guide, maybe we could add them:
- `ByA11yStates`, `ByAccessibilityStates`
- `ByA11yState`, `ByAccessibilityState`
- `ByA11Value`, `ByAccessibilityValue`
Wdyt?
Tested using `yarn start` in the `website/` directory.
=> docs: Port 'How Should I Query?' guide from Native Testing Library

src/__tests__/fireEvent.test.js, src/fireEvent.js
Effectively, wrapping a disabled `Touchable` with a non-responder host element (plain old `View`) will ignore the `disabled` prop. In the example below (same as spec file), `fireEvent.press(screen.getByText('Trigger'));` should not trigger the `handlePress` mock function as the `TestChildTouchableComponent` TouchableOpacity is disabled. Since the wrapping `View` in `TestChildTouchableComponent` is a host element it is then considered the `nearestHostDescendant`. Since it is not disabled then the event will eventually trigger.
The solution was to only pass host elements that are responders as `nearestHostDescendant`'s
```
function TestChildTouchableComponent({ onPress, someProp }) {
return (
<View>
<TouchableOpacity onPress={onPress} disabled={someProp}>
<Text>Trigger</Text> …
```
=> fix: non-responder wrapping host elements ignore disabled prop

website/docs/HowShouldIQuery.md
This addresses #579 
This updates the "How Should I Query?" links to use the correct URLs for each query type. 
I verified these URLs are all correct.
=> fix: Update "How Should I Query?" links to use the correct URLs

typings/index.d.ts
Update the TS types for the new `container` property that was added to the output of `render` in #567.
In a TS project using the current version of @testing-library/react-native (currently 7.1.0), try accessing `container` on the result of a `render` call. A typing error will occur because RenderAPI (the result of `render`) doesn't have a `container` property.
```ts
const bodyText = render(<BodyText>Foo</BodyText>);
expect(bodyText.container).toHaveTextContent('Foo'); // <-- will generate type error
```
With this PR, no error is shown.
=> fix: add container to TypeScript types

typings/__tests__/index.test.tsx, typings/index.d.ts
`debug.shallow()` is something we support, but TS typings were lacking
Added test typings
=> fix: correct TS typings for `shallow.debug`

src/__tests__/fireEvent.test.js, src/fireEvent.js
This enables elements that have onMoveShouldSetResponder returning true, but not onStartShouldSetResponder.
Fixes #576 .
=> Add onMoveShouldSetResponder to element enabled checking

src/helpers/errors.js, src/waitFor.js
This fixes https://github.com/callstack/react-native-testing-library/issues/547 with a solution more or less copied from [this file in dom-testing-library](https://github.com/testing-library/dom-testing-library/blob/master/src/wait-for.js).
A useful stack trace and codeframe are now shown for `findBy` failures.
Note that to get the correct codeframe, the repo running the test must be another that uses this repo as a package, this won't work in the internal tests.
I didn't add any test because I'm not sure assertions on the stack trace make sense...
Contrary to the issue above, the stacktrace was already working with `waitFor` for me, so while it should improve the situation for `waitFor` calls too, I can't be sure of it.
The stack trace still has 2 useless/internal lines, but I suspect to …
=> fix: display stack trace and code frame for findBy error

examples/reactnavigation/src/AppNavigator.js, examples/reactnavigation/src/__tests__/AppNavigator.test.js, examples/reactnavigation/src/screens/DetailsScreen.js, examples/reactnavigation/src/screens/HomeScreen.js, examples/redux/App.js, examples/redux/components/AddTodo.js, examples/redux/components/AddTodo.test.js, examples/redux/components/TodoElem.js, examples/redux/components/TodoList.js, examples/redux/components/TodoList.test.js, src/__tests__/a11yAPI.test.js, src/__tests__/act.test.js, src/__tests__/auto-cleanup-skip.test.js, src/__tests__/auto-cleanup.test.js, src/__tests__/cleanup.test.js, src/__tests__/findByApi.test.js, src/__tests__/fireEvent.test.js, src/__tests__/getByApi.test.js, src/__tests__/jest-native.test.js, src/__tests__/queryByApi.test.js, src/__tests__/questionsBoard.test.js, src/__tests__/render.test.js, src/__tests__/waitFor.test.js, src/__tests__/within.test.js, website/docs/ReactNavigation.md, website/docs/ReduxIntegration.md, website/src/components/Feature.js, website/src/pages/index.js
React won't have a default export in the future, so replacing it with the `import * as React from 'react'` prepares library for that.
Closes #627 
CI
=> chore: update React imports

website/docs/API.md
Hello! 
I had an issue where I was trying to test a SectionList component and I was trying to mock a scroll event but after the scroll event fired the component still never was found. I saw the data in the components props but not showing up to the test query. After chatting with Michał on the discord server he mentioned this was a constant issue he had to teach people about and he suggested changing my initialNumToRender prop or use an e2e test to verify. He also mentioned needing to update the docs at some point since he's had to teach this to people on a regular basis so I figured I'd go ahead and do it for him.
Let me know if there is anything I should change or that might be clearer. [link to discord conversation](https://discord.com/channels/426714625279524876/497332049187962892/7869 …
=> docs update for fireEvent.onScroll()

src/__tests__/__snapshots__/render.test.js.snap, src/__tests__/render.test.js, src/helpers/getByAPI.js
This PR aims to solve [this issue](https://github.com/callstack/react-native-testing-library/issues/649). Basically the issue to fix is that the byDisplayValue helpers don't check the defaultValue prop of TextInputs.
- [ ] If a TextInput only has a defaultValue and no value, getByDisplayValue should find it
=> Fix issue of getByDisplayValue not checking TextInputs defaultValue

src/__tests__/byTestId.test.js, src/__tests__/render.test.js, src/helpers/a11yAPI.js, src/helpers/byDisplayValue.js, src/helpers/byPlaceholderText.js, src/helpers/byTestId.js, src/helpers/byText.js, src/helpers/filterNodeByType.js, src/helpers/findByAPI.js, src/helpers/getByAPI.js, src/helpers/makeA11yQuery.js, src/helpers/queryByAPI.js
This PR aims to solve [this issue](https://github.com/callstack/react-native-testing-library/issues/325). It is the follow up of this [PR](https://github.com/callstack/react-native-testing-library/pull/608)
Tasks:
type (different for get, find, query).
- [ ] maybe group the tests by predicate type instead of query type?
No tests should be added since the API does not change, they only need to be moved to be grouped by predicate type
=> Finish refactoring queries using new query builder makeQueries

src/__tests__/fireEvent.test.js, src/fireEvent.js
This PR allows handling test cases that use `pointerEvents` which was mentioned in #650. I'm not sure if we should also additionally handle the `box-none` value. 
Fixes #650
I've added 3 tests that check pointerEvents `none` and `box-only` and also pointerEvents `none` with nested views.
=> feat: support pointerEvents

website/docs/ReactNavigation.md
In documentation jest-setup.js file from the example, was mentioned as jest-mocks.js. 
Create a [mock file](https://github.com/callstack/react-native-testing-library/blob/master/examples/reactnavigation/jest-setup.js) necessary for your tests: (Now, on click redirects to correct file)
=> Fixed broken link of mock setup file

jest/preset.js, jest/restore-promise.js, jest/save-promise.js, package.json, src/__tests__/timerUtils.js, src/__tests__/timers.test.js, src/__tests__/waitFor.test.js, src/__tests__/waitForElementToBeRemoved.test.js, src/flushMicroTasks.js, src/helpers/getTimerFuncs.js, src/helpers/timers.js, src/waitFor.js, website/docs/API.md
If you use Timer Mocks in your tests and `waitFor` then you cannot `await` this as the timers internal to `waitFor` would be replaced by the mock timers and thus never resolve. This PR borrows techniques from [wait-for-expect](https://github.com/TheBrainFamily/wait-for-expect/blob/master/src/helpers.ts#L6-L30) and [@testing-library/dom](https://github.com/testing-library/dom-testing-library/blob/master/src/helpers.js#L1-L65) to detect if fake timers are in-use, switch back to real timers for a specific call, then re-instate the fake timers using the timer implementation that was present before.
This implementation also ensures that any mocks of `Date` or `Date.now` will not affect `waitFor`.
Outstanding work: update the docs if this lands.
fixes #506 
Added multiple tests to ensure this …
=> fix(breaking): use real timers internally to fix awaiting with fake timers

src/__tests__/fireEvent.test.js, src/fireEvent.js
Idea from: https://github.com/callstack/react-native-testing-library/pull/674#discussion_r584551609
Quote from @thymikee:
```
We actually don't the invokeEvent to be throwable. It supposed to be there as a debugging aid, but the original Testing Library don't have this behavior and here it actually complicates things a little more.
How about removing this behavior altogether in a separate PR and adjusting this one to keep the invokeEvent without the try/catch?
```
=> feat(breaking): do not throw because event handler was not found

typings/index.d.ts
In a project that didn’t allow implicit `any`s, this error would be thrown for `Debug`.
```
Call signature, which lacks return-type annotation, implicitly has an 'any' return type.
```
Use the `yarn run typescript-check`.
I’ve tested this change against a live project and it corrects the error, though perhaps there is a better type?
=> Debug implicit any error

website/docs/ReactNavigation.md
Update docs in the react-navigation example section that broke the test after upgraded to react-native v0.64
=> Update react navigation  docs to support RN-0.64

src/__tests__/render.test.js, src/render.js
Fixes #705
Tested via added unit tests and the failing test provided in #705.
=> fix: wrap unmount in act

src/__tests__/byText.test.js
This shows two failing test cases for #776 
Note that #554 fixes both of them, so if #554 is merged, they can be enabled.
They test themselves 🙂 
Skipped because they fail on current `master`:
=> test: add failing tests for #776

website/docs/MigrationV9.md, website/sidebars.js
As discussed in https://github.com/callstack/react-native-testing-library/discussions/862#discussioncomment-1705927, here is a proposal for the v9 docs. @thymikee let me know if you had something different in mind.
=> Add v9 release docs

website/docs/EslintPLluginTestingLibrary.md, website/sidebars.js
This adds documentation in the website guides section on the compatibility with eslint plugin testing library, as discussed in #295
No test plan
=> docs: add doc on compatibility with eslint-plugin-testing-library

src/__tests__/waitFor.test.js, src/waitFor.js, typings/index.d.ts
Adds the option `onTimeout?: (error: Error) => Error` to the `waitFor` function to match the option in [the non-native React Testing Library](https://testing-library.com/docs/dom-testing-library/api-async/).
I added a new test for this as well.
Useful so that you can do stuff like this:
```ts
await waitFor(() => expect(getSlotMachine().props.accessibilityState.disabled).toBeFalsy(), {
onTimeout: (e) => {
console.log(getSlotMachine().props.accessibilityState.disabled)
expect(wrapper).toMatchSnapshot();
return e;
}
});
```
=> feat: adds onTimeout option to waitFor

website/docs/Queries.md
When pressing the `#TextMatch` link in the [docs](https://callstack.github.io/react-native-testing-library/docs/api-queries/#options) under queries > options we aren't redirected anywhere due to capital letters included in the relative path of the header.
The same issue exists with the `#Normalization` link in the [docs](https://callstack.github.io/react-native-testing-library/docs/api-queries/#precision) under precision.
Due to this the `TextMatch` and `Normalization` are not that visible and might cause confusion 🙈
This pr fixes both links.
You can check the links provided below to test.
|Broken|Fixed|
|---|---|
|https://callstack.github.io/react-native-testing-library/docs/api-queries/#Normalization|https://callstack.github.io/react-native-testing-library/docs/api-queries/#normalization …
=> docs: fix textmatch broken link

src/__tests__/byText.test.js, src/helpers/byText.js
This fixes the issue #866 
There are already two open prs for this issue, #663 and #883 but they seem to be stale. 
As suggested in this comment https://github.com/callstack/react-native-testing-library/pull/883#issuecomment-1008809986, this implementation modifies getChildrenAsText function and tests for Fragment type.
I added several test cases with fragments. It should work as if fragments were not there as far as getByText and queryByText are concerned
=> feat: allow getByText and queryByText to find text nested in fragments

website/docs/API.md
Small change in docs to fix links in `API.md`
Check links correctly navigate
=> fix(docs): links in API.md

src/__tests__/renderHook.test.tsx, src/pure.ts, src/renderHook.tsx, typings/index.flow.js, website/docs/API.md
This pr provides a basic implementation of renderHook as requested in #869. The solution is almost a copy past from the one made in react testing library
Some test cases were added, also inspired from the implementation from react testing library
=> feat: add renderHook function

package.json
Currently, `src/render.tsx` is not being built by Babel, because it was changes to a `tsx` extension, but Babel is only told to build `js` and `ts`.
Also, it seems the out directory is out of date in `package.json`.
It now builds everything.
=> fix: missing jsx/tsx in build

website/docs/API.md
Correct the `renderHook` API docs as `result.error` and `result.all` were not included in the new RTL version of `renderHook`.  I also fixed a typo and renamed a test example to better describe what it is showing (both in the same file).
No testing is required other than reviewing the documentation changes.
=> docs(renderHook): remove references to error and all from renderHook API

website/docs/ReduxIntegration.md
We will test 'AddTodo' and not 'TodoElem'
Add '.test' to the second file as well as for 'AddTodo.test.js'
Not necessary as long as the change only concerns the documentation.
=> docs: fix typo in redux integration

website/docs/API.md, website/docs/Queries.md
Adds table of contents for Queries and APIs pages since they are quite long and hence hard to navigate.
None
=> docs: table of contents for Queries and API pages

website/docs/FAQ.md, website/sidebars.js
Adds FAQ page to the docs and provides answer to question about testing native features in RNTL.
None
=> docs: add FAQ page and native features question

src/__tests__/render.test.tsx, src/pure.ts
=> fix: bring back RenderAPI type

README.md, src/__tests__/screen.test.tsx, src/cleanup.ts, src/pure.ts, src/render.tsx, src/screen.ts, typings/index.flow.js, website/docs/API.md, website/docs/EslintPLluginTestingLibrary.md, website/docs/FAQ.md, website/docs/GettingStarted.md, website/docs/Queries.md, website/docs/ReactNavigation.md, website/docs/ReduxIntegration.md
Simple `screen` implementation to match RTL feature. 
https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-screen
* basic `screen` related tests added
=> feat: add `screen` API

src/matches.ts, src/queries/__tests__/text.test.tsx
This fixes #983.
New lines, that are rendered in RN as separate Lines, are wrongly normalised during testing.
```tsx
const { queryByText } = render(<Text>{"Line 1\nLine 2"}</Text>)
expect(queryByText("Line 1\nLine 2")).toBeDefined()
``` 
I have added 2 new tests to verify the fix is working.
=> fix: queryByText and getByText match newlines and tabs properly

package.json, src/__tests__/waitFor.test.tsx, yarn.lock
Support for React Native 0.69.1.
Resolves #998
All checks and tests pass.
=> chore: update react-native to 0.69.1

README.md, website/docs/API.md, website/docs/UnderstandingAct.md, website/sidebars.js
Our users frequently report cryptic errors related to `act()` function usage, like #379 or #859. In order to address this I've created Understanding Act function document to describe it's why and how to use it. Consider it to be initial version of the document describing the `act` basics, with intention to add more specific information for async act warnings later on.
Please share your thoughts and suggestions to improve this document.
Docs only
I've run docosaurus and manually verified links and layout.
=> docs: create document describing act function and related errors

package.json, yarn.lock
We require Jest 28 now, so it makes sense to pull the pretty-format version that comes along with it.
CI
=> chore: upgrade pretty-format to v28 to match Jest deps

website/docs/MigrationV11.md
I believe there is a typo in page title: `Migration to 1.0` should be `Migration to 11.0`
=> fix(docs): typo in v11 migration guide title

website/docs/MigrationV11.md
Small fix to v11 migration guide changelog link (link to v11.0.0 tag instead of v11.0.0-rc tag).
=> docs: v11 migration changelog link

examples/basic/package.json
Update basic example app to use Expo 46. Should also fix running example apps due to "Jest not exited error"
=> chore: update deps to expo 46

README.md, website/docs/Troubleshooting.md, website/sidebars.js
Let's kick of a troublshooting guide where we will explain how to fix common issues met by our users. Starting with one recent issue.
=> docs: troubleshooting guilde

src/pure.ts, src/render.tsx, src/renderHook.tsx, typings/index.flow.js
Resubmitting #1034 as almost done but have to write access to forked PR-repo and OP @evanwalsh is not responsive.
Original description below:
While writing helpers around the render and renderHook functions, I found myself wanting/needing the types for the options and the returns. This explicitly exports those types that weren't already exposed to avoid having to do something like the following:
```ts
type RenderOptions = Parameters<typeof render>[1]
type RenderHookOptions = Parameters<typeof renderHook>[1]
// Copied/pasted from @testing-library/react-native
interface RenderHookResult<Result, Props> {
result: {current: Result}
rerender: (props: Props) => void
unmount: () => void
}
```
These types are already documented, so this just fully exposes types that are already meant for users. …
=> feature: export options types and renderHook result type

package.json, yarn.lock
Remove outdated and unused `cp-cli` raising dependabot security alerts. 
=> chore: remove cp-cli dep

package.json
Make Jest 28 an optional peer dep.
=> chore: optional jest peer dep

package.json, yarn.lock
Deep update of `conventional-commit-cli` and related deps to resolve dependanbot security alerts.
```
yarn remove conventional-commit-cli
yarn add -D conventional-commit-cli
```
=> chore: remove and add again  `conventional-changelog-cli` to update deep deps

src/__tests__/fireEvent.test.tsx, src/fireEvent.ts, src/helpers/filterNodeByType.ts
Related to issue #476 
It is possible to modify non editable TextInputs when querying them with a testID because the testID queries return host components whose type is of type string, therefore isTextInput is always returning false. This fixes it by checking in isTextInput if the type is either the component TextInput or the string TextInput.  
Added a test case to check non editable text inputs cannot be changed when queried by testID
=> fix: prevent non editable textinputs from being updated through getByTestID

src/__tests__/fireEvent.test.tsx
This PR adds tests for a behaviour we support (triggering event that don't exist on the JS side but are handled natively). It is however not tested, so I want to add test to make sure we don't lose this feature by mistake (see discussions in https://github.com/callstack/react-native-testing-library/pull/1080#issuecomment-1241207946).
=> chore: add test to ensure it is possible to trigger native event

website/docs/API.md
Document `render` options, especially the new `unstable_validateStringsRenderedWithinText` option.
=> docs: document `render` options

src/queries/__tests__/role.test.tsx, src/queries/role.ts, typings/index.flow.js, website/docs/Queries.md
Folllow up of #875. I started from scratch given the amount of conflicts.
Closes #827
If merged as is, don't forget to mention @kiranjd as part of the release.
Kudo to @MattAgn's work in #977 which made that a breeze. Look at the diff between this PR and the previously opened one, the code reorg was def the right call.
=> Add support for ByRole with name

.eslintrc, src/fireEvent.ts, src/helpers/__tests__/accessiblity.test.tsx, src/helpers/__tests__/component-tree.test.tsx, src/helpers/accessiblity.ts, src/helpers/component-tree.ts, src/pure.ts, website/docs/API.md
Implement [`isInaccessible`](https://testing-library.com/docs/dom-testing-library/api-accessibility/#isinaccessible) API from DTL (re-exported from RTL).
This should be a useful building block for features as:
* #1064
* [feat: add toBeVisible matcher #73 from Jest Native](https://github.com/testing-library/jest-native/pull/73)
=> feat: `isInaccessible` API form RTL/DTL

src/__tests__/config.test.ts, src/__tests__/waitFor.test.tsx, src/config.ts, src/pure.ts, src/waitFor.ts, typings/index.flow.js, website/docs/API.md
Implement `configure` API based on [similar API in DTL](https://testing-library.com/docs/dom-testing-library/api-configuration).
Added initial option for [`asyncWaitTimeout`](https://testing-library.com/docs/dom-testing-library/api-configuration/#asyncutiltimeout).
* Added tests for `config` module functions
* Added tests for `waitFor` consuming `asyncWaitTimeout` option
=> feature: configure API from DTL

website/docs/EslintPLluginTestingLibrary.md
Fixes a few minor typos on the page `docs/eslint-plugin-testing-library`
n/a
=> Eslint plugin docs typos

typings/index.flow.js
Adds new option unstable_validateStringsRenderedWithinText to renderOptions type in flow types
I don't know how to test flow types, is there a recommended way to do so ?
=> fix: update render flow type with new option unstable_validateStringsRenderedWithinText

website/docs/Queries.md
Improve documentation by adding expanded type definitions for all queries. This should make our query docs easier to understand. In line with DTL docs, I provided only typedef for `getBy` variant.
None.
=> docs: add typedefs for queries

src/helpers/__tests__/timers.test.ts, src/helpers/timers.ts, website/docs/API.md, website/docs/MigrationV2.md
Allow explicitly disabling automatic jest fake timers detection in order to solve https://github.com/callstack/react-native-testing-library/issues/886
=> Ignore fake timers

src/helpers/accessiblity.ts, src/helpers/matchers/accessibilityState.ts, src/queries/__tests__/a11yState.test.tsx, src/queries/a11yState.ts, src/queries/role.ts, website/docs/Queries.md
Resolves #1165.
Based on empirical research results: https://github.com/callstack/react-native-testing-library/wiki/Accessibility:-State
Added additional test for matching behaviour.
=> fix: *ByA11yState default value false value for busy, disabled & selected state

.circleci/config.yml, .codecov.yml, package.json
=> chore: add codecov

src/__tests__/waitFor.test.tsx, src/waitFor.ts
Fixes #1176 
Use a timeout in waitFor only when using realTimers and timeout with fake timers only after fakeTimeRemaining is over
I added a test case that initially failed. I compute fibonaci suite so that it takes some time to perform the checks (it must take longer than interval for this bug to be visible)
This shouldn't be a breaking change, all tests that previously passed should still do because we're not performing any check after fakeTimeRemaining is over anyway
=> fix: do not use a real timeout in waitfor when using fake timers

src/matches.ts, src/queries/__tests__/hintText.test.tsx, src/queries/__tests__/labelText.test.tsx, src/queries/__tests__/text.test.tsx, src/queries/hintText.ts, src/queries/labelText.ts, src/queries/makeQueries.ts, typings/index.flow.js, website/docs/Queries.md
Changes for [PR](https://github.com/callstack/react-native-testing-library/issues/1182)
=> Add queryOptions to labelText and hintText

src/helpers/__tests__/accessiblity.test.tsx, src/helpers/accessiblity.ts, src/helpers/findAll.ts, src/pure.ts, typings/index.flow.js, website/docs/API.md, website/docs/Queries.md
Rename `isInaccessible` as `isHiddenFromAccessibility`. Then provide RTL-compat alias `isInaccessible`, but only as a secondary option.
Update existing tests to use `isHiddenFromAccessibility`.
=> feat: alias isInaccessible as isHiddenFromAccessibility

examples/basic/__tests__/App.test.tsx, examples/basic/components/Home.tsx, examples/basic/components/LoginForm.tsx, examples/basic/package.json
Update example basic app:
* to use `*ByRole` for relevant queries
* upgrade deps, incl. Expo 47
=> chore: update example basic app

.gitignore, src/__tests__/config.test.ts, src/config.ts, src/helpers/__tests__/component-tree.test.tsx, src/helpers/__tests__/includeHiddenElements.test.tsx, src/helpers/findAll.ts, src/queries/__tests__/a11yState.test.tsx, src/queries/__tests__/a11yValue.test.tsx, src/queries/__tests__/displayValue.test.tsx, src/queries/__tests__/hintText.test.tsx, src/queries/__tests__/labelText.test.tsx, src/queries/__tests__/placeholderText.test.tsx, src/queries/__tests__/role.test.tsx, src/queries/__tests__/testId.test.tsx, src/queries/__tests__/text.test.tsx, src/queries/options.ts, typings/index.flow.js, website/docs/API.md, website/docs/Queries.md
This PR aims to tackle [this issue](https://github.com/callstack/react-native-testing-library/issues/1194). Basically the idea is to add a new option `includeHidden` that will be an alias to the query option `hidden` but much clearer. We keep the old name `hidden` for compatibility with RTL
Resolves #1194
=> Add alias to hidden in query options

src/helpers/__tests__/accessiblity.test.tsx, src/helpers/accessiblity.ts, src/helpers/matchers/accessibilityValue.ts, src/queries/__tests__/a11yValue.test.tsx, src/queries/__tests__/role-value.test.tsx, src/queries/__tests__/role.test.tsx, src/queries/a11yValue.ts, src/queries/role.ts, typings/index.flow.js, website/docs/Queries.md
1. Add `value` option to `*ByRole` query
2. Improve `*ByA11yValue` query by allowing `text` entry to be string or regex
Added relevant tests for `*ByRole` query and `*ByA11yValue`.
=> feat: *ByRole a11y value option

website/docs/Queries.md
Use `includeHiddenElements` option name in docs instead of `hidden`
=> docs: use includeHiddenElements option name instead of hidden

src/__tests__/config.test.ts, src/config.ts, website/docs/API.md
New config option `allowBreakingChanges` that when set to `true` would allow us to introduce breaking changes without need for major release. It has to be opt-in, so that if not set the library works in non-breaking way.
The goal here is to be able to move forward with code changes that introduce breaking changes like #1234 #1180 without blocking other non-breaking developments. When the major release happens we would promote changes enabled by `allowBreakingChanges` optiopn and make the the default. 
I've also have alternative names for the option:
* `useCuttingEdge: true`
* `useLatestApis: true`
* `useVersionNext: true`
* `moveFastAndBreakThings: true`
Pls treat this PR as RFC/discussion I've submitted it as PR because it was low-effort to do it in this way. @pierrezimmermannbam …
=> feat: config option to allow breaking changes

examples/react-navigation/README.md, examples/react-navigation/src/screens/DetailsScreen.js, examples/react-navigation/src/screens/DetailsScreen.test.js, examples/react-navigation/src/test-utils.js
Refactor React Navigation example based on [feedback](https://github.com/callstack/react-native-testing-library/pull/1237#discussion_r1033973998) from @satya164 from React Navigation team.
=> docs: refactor react-navigation example with React Nav team feedback

website/docs/Queries.md
Improve docs in response to #1223 
Read the updated docs.
=> docs: improve findBy docs by adding information about screen.debug()

website/docs/Queries.md
Related to #1209 
Read the relevant changes in the docs.
=> fix: add deprecation notice for *ByA11yState and *ByA11yValue queries

examples/basic/__tests__/App.test.tsx, examples/basic/jest-setup.js, examples/basic/package.json, examples/react-navigation/jest-setup.js, examples/react-navigation/package.json, examples/react-navigation/src/DrawerNavigator.test.js, examples/react-navigation/src/NativeStackNavigator.test.js, examples/react-navigation/src/StackNavigator.test.js, examples/react-navigation/src/TabNavigator.test.js, examples/react-navigation/src/screens/DetailsScreen.test.js, package.json, website/docs/API.md, website/docs/Queries.md, website/docs/ReactNavigation.md, website/docs/ReduxIntegration.md, website/docs/UnderstandingAct.md, yarn.lock
Update docs and examples to use `toBeOnTheScreen()` matcher from Jest Native instead of `toBeTruthy()` matcher.
=> chore: update examples to use toBeOnTheScreen()

src/__tests__/host-component-names.test.tsx, src/helpers/__tests__/accessiblity.test.tsx, src/helpers/accessiblity.ts, src/helpers/host-component-names.tsx, src/queries/__tests__/role-value.test.tsx, src/queries/__tests__/role.breaking.test.tsx, src/queries/__tests__/role.test.tsx, src/queries/role.ts
Solves #1180. It makes byRole queries return only implicit or explicit accessibility elements. Explicit accessibility elements are those with `accessibility` prop set to true. Implicit accessibility elements are `Text`, `TextInput`, `Pressable` and `Switch` (tested with VoiceOver for `Switch` to check it was indeed accessible even without setting the accessible prop and I checked through a snapshot, behing the scene, Switch resolves to a host component RCTSwitch).
=> byRole queries return only accessibility elements

package.json, src/helpers/matchers/matchLabelText.ts, src/helpers/matchers/matchTextContent.ts, src/matches.ts, src/queries/__tests__/labelText.test.tsx, src/queries/__tests__/text.breaking.test.tsx, src/queries/__tests__/text.test.tsx, src/queries/labelText.ts, src/queries/testId.ts, src/queries/text.ts, website/docs/Queries.md
Adds support for [accessibilityLabelledBy](https://reactnative.dev/docs/accessibility#accessibilitylabelledby-android) in `*ByLabelText` queries as in #1183.
=> feat: check accessibilityLabelledBy in *ByLabelText queries

package.json, src/__tests__/act.test.tsx, src/act.ts
Resolve typing issues with `act` by allowing to invoke both `act()` and `await act()`. React `act` has uses function overloading which is hard to work with, so I've resorted to casting.
Dropping support for mock `act` and increasing peer dep req to [React 16.8](https://github.com/facebook/react/releases/tag/v16.8.0) (earliest version to expose act in Test Renderer). I think we can avoid calling this a breaking change, as we already specified minimal RN version of 0.59, which uses React 16.8.3 ([see here](https://docs.google.com/presentation/d/1Z8mNkRw5CJ93qSQqESrcXbgia1dA8V1olnpKT0lsygk/edit#slide=id.gdc26277501_0_39))
Resolves #1276 
Resolves #1207
Typecheck runs fine.
=> fix: force cast await to proper type

src/helpers/__tests__/query-name.test.ts, src/helpers/deprecation.ts, src/helpers/query-name.ts, src/queries/__tests__/a11yState.test.tsx, src/queries/__tests__/a11yValue.test.tsx, src/queries/a11yState.ts, src/queries/a11yValue.ts, website/docs/API.md, website/docs/Queries.md
Make `*ByA11yState` and `*ByA11yValue` queries deprecated, redirecting user to use `*ByRole` queries or `toHaveAcessbibilityState/Value()` matchers.
When doing any of the mentioned queries, user will received following warning to console:
```
getByA11yValue(...) is deprecated and will be removed in the future.
Use expect(...).toHaveAccessibilityValue(...) matcher o rgetByRole(role, { value: ... }) query instead.
```
```
getByAccessibilityState(...) is deprecated and will be removed in the future.
Use getByRole(role, { disabled, selected, checked, busy, expanded }) query or expect(...).toHaveAccessibilityState(...) matcher instead.
```
Resolves #1208
Add tests for deprecation messages warnings.
=> chore: deprecate some a11y queries

src/__tests__/host-component-names.test.tsx, src/helpers/host-component-names.tsx, src/render.tsx
This is based on #1304, but since that was external PR I've moved it as internal repo PR with added proposed changes:
* extract `detectHostElementNames` from `getHostComponents()`
* create `configureHostElementNamesIfNeeded` to be called in `render`
* simplify `getHostElementNames`.
Summary
Fixes https://github.com/callstack/react-native-testing-library/issues/1302 by detecting host component names in `render` to prevent running auto detection in external `act` which fails for some users.
Test plan
Added a test case where I call getHostComponentNames wrapped in act after a render and expect it does not throw
=> fix: get host component names on render (modified)

src/__tests__/__snapshots__/render.breaking.test.tsx.snap, src/__tests__/__snapshots__/render.test.tsx.snap, src/__tests__/render.breaking.test.tsx, src/__tests__/render.test.tsx, src/__tests__/screen.test.tsx, src/queries/__tests__/displayValue.breaking.test.tsx, src/queries/__tests__/placeholderText.breaking.test.tsx, src/render.tsx, src/screen.ts, typings/index.flow.js, website/docs/API.md, website/docs/Queries.md
This PR contains breaking changes behind `useBreakingChanges` feature flag.
Resolves #1296 
1. Rename `container` to `UNSAFE_root`
2. Display deprecation messages for `container` (behind `useBreakingChanges` )
3. Expose `root` API that returns root host element.
All tests pass.
=> refactor(breaking): rename `container` to `UNSAFE_root`; introduce `root` host element

examples/basic/jest-setup.js, examples/react-navigation/README.md, examples/react-navigation/jest-setup.js, src/__tests__/config.test.ts, src/config.ts, src/helpers/__tests__/accessiblity.test.tsx, src/helpers/accessiblity.ts, src/queries/__tests__/a11yState.test.tsx, src/queries/__tests__/a11yValue.test.tsx, src/queries/__tests__/displayValue.test.tsx, src/queries/__tests__/hintText.test.tsx, src/queries/__tests__/labelText.test.tsx, src/queries/__tests__/placeholderText.test.tsx, src/queries/__tests__/role.test.tsx, src/queries/__tests__/testId.test.tsx, src/queries/__tests__/text.test.tsx, website/docs/API.md, website/docs/MigrationV12.md, website/docs/Queries.md
All checks should pass. Pls review testing code.
=> [v12] refactor: exclude hidden elements by defaults

README.md, website/docs/API.md
Based on #1307
Updates docs to specify that jest preset is no longer required for users that have a version of react native >= 0.71.2
=> docs: update docs on custom jest preset

website/docs/MigrationV12.md
Updates migration guide for v12 to include update of jest-native when using `toBeOnTheScreen` matcher
=> docs: update v12 migration guide

src/__tests__/render.test.tsx, src/__tests__/screen.test.tsx, src/render.tsx, src/screen.ts
Make deprecated `container` property non enumerable to avoid triggering exception when used in e.g. object rest destructuring.
Resolves #1350.
Added unit test for rest destructuring.
=> fix: container enumeration

src/helpers/matchers/accessibilityState.ts, src/queries/a11yState.ts, src/queries/role.ts
Duplicate `AccessibilityState` type as `AccessibilityStateMatcher` type in order to avoid issues occurring during migration period from `@types/react-native` to built-in `react-native` types. See #1351 for details.
This fix will be first applied to v12 branch to verify that it fixes the issue, and later will be backported to v11.
Resolves #1351
Verification by @AugustinLF after v12 RC2 is released.
=> fix: resolve AccessibilityState import issue due to types migration to `react-native` package

src/helpers/matchers/accessibilityState.ts, src/queries/a11yState.ts, src/queries/role.ts
Cherry pick of #1355 to `main`.
=> fix: duplicate AccessibilityState type (#1355)

src/__tests__/render.test.tsx, src/helpers/__tests__/getTextContent.test.tsx, src/render.tsx
Resolves #1350 on `main`
```ts
const { something, ...rest } = render(...)
```
Above code, frequently used for building custom render functions, triggers `container` console warning, as rest operator causes `container` property to be read and hence the error logged. To avoid this unnecessary and not actionable noise for the users I disabled the console warning.
=> fix: disable container deprecation warning (main)

src/__tests__/waitFor.test.tsx, src/flushMicroTasks.ts, src/waitFor.ts
It can happen that a `waitFor` call like
```js
await waitFor(() => getByText('green'));
```
successfully returns because the `"green"` text has been rendered, but after returning, the effects or state updates scheduled by the `"green"` render haven't been executed yet.
That's because `waitFor` internally leaves the `act` environment for a moment, lets a render to be performed and to schedule updates outside the `act` queue, and then returns before these updates were flushed.
I'm submitting a test that exposes this bug, using a series of cascaded effects and state updates, and also a fix.
Accidentally, @eps1lon landed almost exactly the same fix to `@testing-library/react` a month ago: https://github.com/testing-library/react-testing-library/pull/1137. But I discovered the React Native bug …
=> Flush all pending microtasks and updates before returning from waitFor

src/helpers/host-component-names.tsx, src/render-act.ts, src/render.tsx
Fixes a bug that I discovered while working on #1366: when first calling `render` in a test suite, the `render` function calls `detectHostComponentNames`, which mounts a testing tree with a few components. This tree is rendered outside the `act` environment, and therefore schedules a `setImmediate` callback to process effects. This scheduled callback then has an unwanted interaction with my actual testing code. If there is a `waitFor` inside my test, the effects scheduled by _my_ testing code will not be processed by _my_ `setImmediate`, but by the one scheduled by `detectHostComponentNames`. That makes the precise order of events inside my test non-deterministic and unpredictable.
Look at this call stack:
and note how it starts in my `waitFor.test.ts` test, in the `render` function, then …
=> detectHostComponentNames: render test tree inside act to avoid timer leaks

website/docs/MigrationV12.md
Fixes a small typo in the v12 migration guide, the word "derived"
n/a
=> Fix typo in "derived" in v12 migration guide

website/docs/MigrationV12.md
=> chore: fix migration guide role prop naming

website/docusaurus.config.js
The documentation contains a link at the bottom of each page: "Edit this page". The link was resulting in a 404 because Docusaurus was not configured with the proper path.
* Before (404): https://github.com/callstack/react-native-testing-library/blob/main/docs/FAQ.md (as seen from [this page](https://callstack.github.io/react-native-testing-library/docs/faq))
* After: https://github.com/callstack/react-native-testing-library/blob/main/website/docs/FAQ.md
I built the documentation, per the readme, and verified the link now works.
=> fix: "Edit this Page" link in docs results in 404

src/queries/makeQueries.ts
`findBy*` and `findAllBy*` queries reported `waitFor` stack trace callsite instead of their own. This fixes it.
Before:
After:
Manually run a `findBy*` and `findAllBy*` test to view the stacktrace reported by Jest.
=> fix: proper stack trace for findBy* and findAllBy* queries

src/__tests__/fireEvent.test.tsx, src/fireEvent.ts
Resolves #1387
This PR changes how `pointerEvents` checks are evaluated. Previously they were done on both host and composite elements which resulted in a case when composite `Pressable` with `pointerEvents="box-only"` would block `press` event on host `View` it was returning. The fix is to check `pointerEvents` only on host components.
In addition to the fix, I've cleaned up test related to pointer events and refactored `isPointerEventEnabled` for readability.
Add new test suggested in #1387
=> fix: pointer events evaluation

src/helpers/deprecation.ts, src/helpers/errors.ts
Move deprecation functions, disable code cov for not used ones.
N/A
=> chore: move/remove deprecation functions

src/__tests__/config.test.ts, src/__tests__/host-component-names.test.tsx, src/__tests__/react-native-api.test.tsx, src/config.ts, src/helpers/__tests__/component-tree.test.tsx, src/helpers/accessiblity.ts, src/helpers/component-tree.ts, src/helpers/host-component-names.tsx
=> refactor: component tree dead code

src/__tests__/fireEvent.test.tsx, src/fireEvent.ts, src/helpers/component-tree.ts
Scope:
Improved existing pointer event test by using both event forms `press` and `onPress.
=> refactor: `fireEvent` cleanup

src/__tests__/fireEvent-textInput.test.tsx, src/__tests__/fireEvent.test.tsx, src/fireEvent.ts
[Description by @mdjastrzebski]
This PR modifies the `fireEvent` handling for `TextInputs` by checking the `editable` prop status of the nearest touch responder of given element. The nearest touch responder is the nearest descendant element that is both host element as well as advertises as touch responder. One such element is `TextInput`.
The previous version of the code, checked the `editable` prop status on the element itself, which could lead to situations when `TextInput` wrappers would execute events, e.g. `changeText`, `focus`, etc on non-editable `TextInput`, because the check has been limited to host `TextInput` and wrapping it composite `TextInput` coming from RN package. Any additional `TextInput` wrapper would not have it's `editable` prop checked and would refer to host …
=> fix: non-editable wrapped TextInput events

src/__tests__/fireEvent-textInput.test.tsx, src/fireEvent.ts
This fixed an edge case when user would use `onLayout` event handler name instead of `layout` event name with `fireEvent` and that would skip the `editable` prop check.
Additionally, refactored event array checks to use `Set` type.
Added test code to detect the fixed scenario.
=> fix:  support `onXxx` event name for TextInput event checks

.codecov.yml
It's super annoying to get dozens of meaningless codecov notifications in my inbox every day, because of the current behavior. Switching to default to "update, if exists. Otherwise post new"
Ref: https://docs.codecov.com/docs/pull-request-comments#behavior
Codecov updates instead of recreating the comment
=> chore: switch Codecov PR comment to default behavior

src/pure.ts, src/render.tsx
This Pull Request addresses a problem encountered when trying to use a custom render function in TypeScript. The issue throws an error:
"Exported variable 'customRender' has or is using name 'DebugFunction' from external module '/node_modules/@testing-library/react-native/build/render' but cannot be named."
To resolve this problem, we're exporting the DebugFunction interface from the module it's declared in. This change will allow the TypeScript compiler to recognize the DebugFunction type when it's used in external modules, thus eliminating the naming error that is currently being thrown.
The error:
With this change the error goes away:
The error can be solved in the custom render by using `RenderResult` as the return type, but it'd be nice to work directly. 😀
=> fix: fixing TypeScript accessibility issue for custom render function

src/__tests__/render.test.tsx, src/__tests__/renderHook.test.tsx, src/helpers/accessiblity.ts, src/render.tsx, src/renderHook.tsx
https://github.com/callstack/react-native-testing-library/issues/1423
This change can be tested by running the renderHook.test.tsx tests after clearing the jest cache. Before my change, the first test takes 445 ms and after my change it takes 5 ms. 
Before: 
``` ~/Code/react-native-testing-library   main  yarn jest ./src/__tests__/renderHook.test.tsx
yarn run v1.22.19
$ ~/Code/react-native-testing-library/node_modules/.bin/jest ./src/__tests__/renderHook.test.tsx
PASS  src/__tests__/renderHook.test.tsx
✓ gives comitted result (445 ms)
✓ allows rerendering (1 ms)
✓ allows wrapper components (2 ms)
Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        1.273 s
Ran all test suites matching /.\/src\/__tests__\/renderHook.test.tsx/i.
✨  Done in …
```
=> fix: add prop to render to skip configureHostComponentNamesIfNeeded

examples/basic/package.json, examples/react-navigation/README.md, examples/react-navigation/package.json, examples/redux/README.md, examples/redux/package.json
Update deps in examples. Mark React Navigation and Redux examples as stale.
=> chore: update example deps

src/user-event/press/__tests__/press.test.tsx, src/user-event/press/press.ts
Fixed small issues with `UserEvent.press()`:
* `longPress` should call `onLongPress` on `Text` element
* avoid calling `onPress` on `TextInput` as it's not supported
* consider `Text` to pressable if it has any press-related event handler
Added `longPress` tests for `Text` and `TextInput`
=> fix: UserEvent longPress on Text component

src/pure.ts, src/user-event/index.ts, website/docs/API.md, website/docs/UserEvent.md, website/sidebars.js
This PR exposes publicly User Event API and documentation.
Check website sidebar.
=> chore: expose User Event in the exports and website

experiments-app/src/experiments.ts, experiments-app/src/screens/FlatListEvents.tsx, experiments-app/src/screens/ScrollViewEvents.tsx, experiments-app/src/screens/SectionListEvents.tsx
I added an experiment for `ScrollView`.
I simply copied the example from official docs https://reactnative.dev/docs/scrollview and attached logger for every event prefixed with 'on' word.
I'm marking it as draft for now as I plan to continue with `FlatList` and `SectionList` within the same PR.
=> ScrollView experiments

experiments-app/package.json, experiments-app/src/MainScreen.tsx, experiments-app/src/experiments.ts, experiments-app/src/screens/FlatListEvents.tsx, experiments-app/src/screens/ScrollViewEvents.tsx, experiments-app/src/screens/SectionListEvents.tsx, experiments-app/src/screens/TextInputEventPropagation.tsx, experiments-app/src/screens/TextInputEvents.tsx, experiments-app/src/utils/helpers.ts, experiments-app/yarn.lock
Scope:
* add logging of micro and macro tasks enqueued during event processing.
* update Expo deps for experiments app
Experiments results are described [here](https://github.com/callstack/react-native-testing-library/wiki/TextInput-Events#micro--macro-tasks-after-events). TLDR: we should flush micro tasks after each emitted event. Macro task behavior vary, but for simplicity we should also flush these as well.
None
=> chore: experiments app tweaks

website/docs/Queries.md
1. Add note about accessibility element status required for `*ByRole` queries.
2. Move `*ByRole` queries up
=> chore: update docs

src/user-event/__tests__/__snapshots__/clear.test.tsx.snap, src/user-event/__tests__/clear.test.tsx, src/user-event/clear.ts, src/user-event/index.ts, src/user-event/press/press.ts, src/user-event/setup/setup.ts, src/user-event/type/__tests__/type-managed.test.tsx, src/user-event/type/__tests__/type.test.tsx, src/user-event/type/type.ts, src/user-event/utils/__tests__/wait.test.ts, src/user-event/utils/host-components.ts, src/user-event/utils/index.ts, src/user-event/utils/text-range.ts, website/docs/UserEvent.md
Method for clearing the content of `TextInput` element. This method is useful as `type()` helper, following OG User Event implementation, is appending text and not replacing it. Hence, users need a way to clear it in some cases. Currently they have to resort to `fireEvent.changeText(element, '')` workaround.
Added tests based on subset `type()` tests.
=> feature: userEvent `clear()`

src/fireEvent.ts, src/helpers/component-tree.ts, src/helpers/filterNodeByType.ts, src/helpers/findAll.ts, src/helpers/host-component-names.tsx, src/helpers/matchers/matchLabelText.ts, src/queries/a11yState.ts, src/queries/a11yValue.ts, src/queries/displayValue.ts, src/queries/hintText.ts, src/queries/labelText.ts, src/queries/makeQueries.ts, src/queries/placeholderText.ts, src/queries/role.ts, src/queries/testId.ts, src/queries/text.ts, src/render.tsx
- Updates the return type of all queries to `HostReactTestInstance`
- Moves logic of filtering non host elements in `findAllInternal` rather than on each query level
Now that all queries return host elements, this can be made explicit by a more precise typing. It also ensures that queries will consistently return host elements from now on. I also moved the logic of filtering non host elements in `findAllInternal` rather than on each query level to remove some code duplication and most importantly remove checks that didn't use `isHostElement` and therefore were not explicit.
All existing tests and type checks pass
=> refactor: type all queries to return host components

package.json
Seems like negative `files` entries confuse Yarn, so that it bundles all folders (e.g. `website`, `examples`, etc in the NPM package).
https://packagephobia.com/result?p=@testing-library/react-native@12.1.3
Fixes #1452 
See [Yarn issue](https://github.com/yarnpkg/yarn/issues/8332)
=> chore: remove negative "files" entry which confused Yarn

jest-setup.ts, jest.config.js, package.json, src/helpers/format.ts, src/queries/__tests__/text.test.tsx, yarn.lock
Replace manual snapshot stripping of terminal color codes with proper Jest plugin.
All existing checks to pass.
=> chore: Jest snapshot pluging for strip ansi

babel.config.js, package.json, src/__tests__/__snapshots__/render-debug.test.tsx.snap, src/__tests__/react-native-api.test.tsx, src/__tests__/render.test.tsx, yarn.lock
Fixes #1449
Because of the babel plugin for class properties (see this [comment on the react native repo](https://github.com/facebook/react-native/issues/34783#issuecomment-1414609922)), rendering a flatlist would result in an error. Removing the plugin fixes the error, although I'm not sure why because that plugin is included in babel/preset-env for versions > 7 so we should have it no matter what. It may be an issue with different versions of the plugin, I haven't really understood what was the exact problem, I've tried to look at the transpiled files using the babel cli but they look exactly the same 
I added a test case for rendering a flatlist and all tests are passing
=> fix: flatlist not rendering in rntl repo

src/matchers/__tests__/to-be-empty-element.test.tsx, src/matchers/__tests__/utils.test.tsx, src/matchers/extend-expect.d.ts, src/matchers/extend-expect.ts, src/matchers/index.tsx, src/matchers/to-be-empty-element.tsx, src/matchers/utils.tsx
=> feat: `toBeEmptyElement` matcher

website/docs/MigrationV12.md
The "Migration to 12.0" guide contained a broken link to GitHub's compare feature.
=> Fix changelog commit range in v12 migration guide

src/helpers/__tests__/format-default.tsx, src/helpers/accessiblity.ts, src/helpers/format-default.ts, src/queries/__tests__/makeQueries.test.tsx, website/docs/API.md
Finish support for `aria-hidden` prop. Note parts of `aria-hidden` support were added in #1465. 
Updated relevant tests.
=> feat: support aria-hidden prop

src/helpers/accessiblity.ts, src/helpers/format-default.ts, src/queries/__tests__/role.test.tsx, src/queries/role.ts, website/docs/Queries.md
Add support for ARIA-compat `role` props.
Added & updated relevant tests.
=> feat: support `role` prop

src/helpers/__tests__/format-default.test.tsx, src/helpers/accessiblity.ts, src/helpers/format-default.ts, src/helpers/matchers/matchLabelText.ts, src/matches.ts, src/queries/__tests__/labelText.test.tsx, src/queries/__tests__/makeQueries.test.tsx, src/queries/__tests__/role.test.tsx, src/queries/labelText.ts, website/docs/Queries.md
Add support for `aria-label` & `aria-labelledby` props.
Added & updated relevant tests.
=> feat: support `aria-label` and `aria-labelledby` props

src/helpers/__tests__/format-default.test.tsx, src/helpers/format-default.ts, src/matchers/__tests__/to-be-disabled.test.tsx, src/matchers/__tests__/to-be-visible.test.tsx, src/matchers/extend-expect.d.ts, src/matchers/extend-expect.ts, src/matchers/to-be-disabled.tsx, src/matchers/utils.tsx, src/queries/__tests__/a11yState.test.tsx, src/queries/__tests__/hintText.test.tsx, src/queries/__tests__/labelText.test.tsx, src/queries/__tests__/makeQueries.test.tsx, src/queries/__tests__/role.test.tsx
Implement `toBeDisabled` matcher
Added relevant tests.
=> feat: `toBeDisabled` matcher

src/matchers/__tests__/to-be-disabled.test.tsx, src/matchers/__tests__/to-be-empty-element.test.tsx, src/matchers/__tests__/to-be-on-the-screen.test.tsx, src/matchers/__tests__/to-have-display-value.test.tsx, src/matchers/__tests__/to-have-prop.test.tsx, src/matchers/extend-expect.d.ts, src/matchers/extend-expect.ts, src/matchers/to-have-prop.ts, src/matchers/utils.tsx
Implement `toHaveProp` matcher
`yarn test`
=> feat: `toHaveProp` matcher

src/helpers/accessiblity.ts, src/matchers/__tests__/to-be-checked.test.tsx, src/matchers/__tests__/to-be-partially-checked.test.tsx, src/matchers/extend-expect.d.ts, src/matchers/extend-expect.ts, src/matchers/index.tsx, src/matchers/to-be-checked.tsx, src/matchers/to-be-disabled.tsx, src/matchers/to-be-partially-checked.tsx
=> feat: `toBeChecked` & `toBePartiallyChecked` matcher

src/__tests__/react-native-api.test.tsx, src/helpers/__tests__/accessiblity.test.tsx, src/helpers/__tests__/format-default.test.tsx, src/helpers/accessiblity.ts, src/helpers/format-default.ts, src/queries/__tests__/makeQueries.test.tsx, website/docs/API.md
Add support for `aria-modal` prop.
Added & updated relevant tests.
=> feat: `aria-modal` support

experiments-app/src/experiments.ts, experiments-app/src/screens/Accessibility.tsx
Added new experiment to the exeperiments app for checking acccessibility behavior.
None.
=> chore: add accessibility experiments

src/helpers/accessiblity.ts, src/matchers/__tests__/to-be-selected.test.tsx, src/matchers/extend-expect.d.ts, src/matchers/extend-expect.ts, src/matchers/index.tsx, src/matchers/to-be-selected.ts
Implement `toBeSelected` : check that the accessibilityState props is "selected".
- toBeSelected works, .not.toBeSelected works
- Display the propers error message if the test fail
=> feat: implement `toBeSelected` matcher

src/helpers/accessiblity.ts, src/matchers/__tests__/to-be-busy.test.tsx, src/matchers/__tests__/to-be-selected.test.tsx, src/matchers/extend-expect.d.ts, src/matchers/extend-expect.ts, src/matchers/index.tsx, src/matchers/to-be-busy.tsx, src/matchers/to-be-selected.ts
Implement new matcher `toBeBusy()`
`yarn test`
=> feat: `toBeBusy()` matcher

website/docs/UserEvent.md
I had to go through the changelog to figure out what version of RNTL I needed to use user-event, as simply being on the latest major isn't sufficient (12.0.1). I thought this might save others time/frustration.
Make sure the updated docs look okay and are clear.
=> docs: note required RNTL version for user-event in user-event.md

website/docs/Troubleshooting.md
Added docs on troubleshooting "undefined component error".
=> docs: troubleshooting undefined components

src/matchers/__tests__/to-contain-element.test.tsx, src/matchers/extend-expect.d.ts, src/matchers/extend-expect.ts, src/matchers/index.tsx, src/matchers/to-contain-element.tsx, src/matchers/utils.tsx
https://github.com/callstack/react-native-testing-library/issues/1486 - Implement `toContainElement()` matcher.
Based on [Jest Native's toContainElement()](https://github.com/testing-library/jest-native/blob/main/src/to-contain-element.ts)
`yarn test`
=> feat: `toContainElement` matcher

src/helpers/accessiblity.ts, src/matchers/__tests__/to-be-collapsed.test.tsx, src/matchers/__tests__/to-be-expanded.test.tsx, src/matchers/extend-expect.d.ts, src/matchers/extend-expect.ts, src/matchers/index.tsx, src/matchers/to-be-collapsed.tsx, src/matchers/to-be-expanded.tsx
Part of Jest matchers migration
Following the example of https://github.com/callstack/react-native-testing-library/pull/1493
`yarn test`
=> feat: `toBeExpanded` matcher

.github/workflows/main.yml, package.json
Disable React 17 tests on CI, as they were always failing due to snapshot miss match as well of some unsupported features like the new ARIA props. On the other hand the way the test script has been written quietly consumed this failure, so that React 17 tests always indicated success.
I've tried to disable just this tests on the CI but could not overcome following error (local & CI):
```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:
●  MESSAGEPORT
1 | // This file and the act() implementation is sourced from react-testing-library
2 | // https://github.com/testing-library/react-testing-library/blob/c80809a956b0b9f3289c4a6fa8b5e8cc72d6ef6d/src/act-compat.js
> 3 | import { act as reactTestRendererAct } from 'react-test-renderer';
| ^
4 | import { …
```
=> fix: disable React 17 tests

README.md
Fix broken hyperlink in README.md. Encountered 404 with the old URL link.
=> fix: change broken hyperlink in README.md

README.md, website/docs/JestMatchers.md, website/docs/MigrationJestMatchers.md, website/docs/Queries.md
Create API docs & migration guide for built-in Jest matchers.
This will not be made public yet, until all of the matchers are migrated and verified. 
Read the docs.
=> docs: Jest matchers docs

package.json, src/__tests__/act.test.tsx, src/__tests__/render-hook.test.tsx, src/__tests__/timer-utils.ts, src/__tests__/wait-for-element-to-be-removed.test.tsx, src/__tests__/wait-for.test.tsx, src/fire-event.ts, src/helpers/__tests__/timers.test.ts, src/index.ts, src/matchers/__tests__/to-have-accessible-name.test.tsx, src/queries/__tests__/accessibility-state.test.tsx, src/queries/__tests__/accessibility-value.test.tsx, src/queries/__tests__/label-text.test.tsx, src/queries/__tests__/make-queries.test.tsx, src/render-act.ts, src/render.tsx, src/user-event/__tests__/clear.test.tsx, src/user-event/setup/setup.ts, src/user-event/utils/dispatch-event.ts, src/wait-for-element-to-be-removed.ts, src/wait-for.ts, yarn.lock
=> Dependabot/npm and yarn/callstack/eslint config 14.0.0

examples/basic/package.json, examples/basic/yarn.lock, examples/react-navigation/package.json, examples/react-navigation/yarn.lock, examples/redux/package.json, examples/redux/yarn.lock
=> chore: update & check example packages

website/docs/FAQ.md, website/docs/GettingStarted.md
Passed some of the docs through Grammarly to improve writing quality.
=> docs: spell-check some docs

.vscode/settings.json, website/docs/HowShouldIQuery.md, website/docs/Queries.md, website/sidebars.js, website/yarn.lock
Rewrite How should I query? guide
Proof-read the docs, check the internal and external links.
=> docs: rewrite How should I query? guide

src/matchers/extend-expect.d.ts
Fixes #1534 
It moves are dependant types definitions for things like `Style`, `AccessibilityValueMatcher`, etc to inside the file, are referencing other  TS did not seem to work.
This is more of a workaround, as we now have mentioned types declared twice, so it would be to refactor it later to work it more automatically.
=> chore: fix extend-expect.d.ts types by internalizing them

src/matchers/__tests__/to-have-text-content.test.tsx, src/matchers/extend-expect.ts, src/matchers/types.ts
Clean up TS issues reported in #1534 without duplicating type declarations.
This solution is modeled on approach used in Jest Expect package: https://github.com/jestjs/jest/blob/main/packages/jest-expect/src/types.ts
=> fix: matcher Jest extensions

README.md, website/docs/CommunityResources.md, website/sidebars.js
=> docs: update community resources

.github/actions/setup-deps/action.yml, .github/actions/setup-website-deps/action.yml, .github/workflows/deploy-website.yml, .github/workflows/example-apps.yml, .github/workflows/main.yml
Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3, actions/cache@v3.
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
run workflows...
=> Node.js 16 actions are deprecated.

website/docs/UserEvent.md
Fix typo in UserEvent.md where `ScrollView` is written as `ScrolLView`
N/A
=> fix typo in UserEvent.md

website/docs/Queries.md
=> docs: improve api docs

src/queries/__tests__/find-by.test.tsx, src/queries/make-queries.ts, src/screen.ts
Fixes error on access to detached `screen` object in `findBy` calls.
Resolves #1572
=> fix: find by timeout with detached screen

website/docs/GettingStarted.md
Use `overrides: []` to apply eslint rules for test files only
...
=> Apply `eslint-plugin-testing-library` for test files only

src/helpers/wrap-async.ts, src/render-act.ts, src/user-event/press/__tests__/press.real-timers.test.tsx, src/user-event/press/__tests__/press.test.tsx, src/user-event/press/press.ts
`renderWithAct` didn't used the right `act` method. It used the one straight from React Test Renderer, instead of our internal `act` which has support for `global.IS_REACT_ACT_ENVIRONMENT` and React 18
All test should pass.
=> fix: proper act usage

src/render-act.ts, src/render.tsx, typings/index.flow.js, website/docs/Render.md
=> refactor: pass through Test Renderer options

README.md, package.json
=> chore: readme tweaks

README.md, website/docs/12.x/index.md, website/rspress.config.ts
=> docs: fix links

.github/workflows/example-apps.yml, examples/basic/.eslintrc, examples/basic/components/LoginForm.tsx, examples/basic/package.json, examples/basic/theme.ts, examples/basic/yarn.lock
=> chore: enable examples workflow

src/matchers/__tests__/to-be-visible.test.tsx, src/matchers/to-be-visible.tsx
`toBeVisible()` can throw error when `StyleSheet.flatten()` returns `undefined` in some edge cases. This PR allows for `undefined` and prevents the error.
Added tests that triggered error.
=> fix: toBeVisible edge case for style values

.codecov.yml, src/test-utils/events.ts, src/user-event/__tests__/clear.test.tsx, src/user-event/clear.ts, src/user-event/press/__tests__/press.real-timers.test.tsx, src/user-event/press/__tests__/press.test.tsx, src/user-event/type/__tests__/type-managed.test.tsx, src/user-event/type/__tests__/type.test.tsx, src/user-event/type/type.ts
This PR modifies the `type()` function to respect the `maxLength` prop of the input element. If the current text length exceeds the `maxLength` value, typing events will not be emitted. This ensures that the input value does not exceed the specified maximum length.
Resolves #1239
1. Create an input element with a `maxLength` prop.
2. Use the `type()` function to input text that exceeds the `maxLength` value.
3. Verify that the input value does not exceed the specified maximum length.
4. Check that no typing events are emitted once the `maxLength` is reached.
Additionally, see that `yarn test` passes with an additional test added to `src/user-event/type/__tests__/type.test.tsx`
=> fix: Respect maxLength prop in type() function

src/user-event/__tests__/__snapshots__/paste.test.tsx.snap, src/user-event/__tests__/paste.test.tsx, src/user-event/index.ts, src/user-event/paste.ts, src/user-event/setup/setup.ts, website/docs/12.x/docs/api/events/user-event.mdx
User Event `paste()` function with following signature:
```ts
function paste(element: ReactTestInstance, text: string);
```
This function simulates user interaction when user focuses a text input, (select all text if present), pastes given text, and finally leaves the text input.
In the basic for no options are accepted but if needed, they might be added in a future PRs.
[Experimental event sequence](https://github.com/callstack/react-native-testing-library/wiki/TextInput-Events).
The signature of the function is based on User Event [v13 variant](https://testing-library.com/docs/user-event/v13/#pasteelement-text-eventinit-options): `paste(element, dataOrText)` and not User Event [v14 variant](https://testing-library.com/docs/user-event/clipboard#paste): `paste(dataOrText)`. 
Although we …
=> feat: user event paste

website/docs/12.x/docs/api/render.mdx
I believe there is a missing assignment in the docs.
=> docs: add missing assignment in render.mdx

src/__tests__/fire-event.test.tsx, src/cleanup.ts, src/fire-event.ts, src/helpers/text-input.ts, src/native-state.ts, src/render.tsx, src/user-event/__tests__/clear.test.tsx, src/user-event/__tests__/paste.test.tsx, src/user-event/paste.ts, src/user-event/type/__tests__/type.test.tsx, src/user-event/type/type.ts
This PR introduces the concept of simulated native view state. The PR supports tracking the value of host `TextInput` elements. 
```
test('sets native state value for unmanaged text inputs', async () => {
render(<TextInput testID="input" />);
const user = userEvent.setup();
const input = screen.getByTestId('input');
expect(input).toHaveDisplayValue('');
await user.type(input, 'abc'); // or fireEvent.changeText(input, 'abc')
// Below assertion now passes
expect(input).toHaveDisplayValue('abc'); 
});
```
This PR supports setting native state value through `fireEvent.changeText` and  User Event `type()`, `clear()` and `paste()` methods.
When `TextInput` is managed through `value` prop, that value takes precedence over simulated native value.
Add
=> feat: simulated native TextInput state

website/docs/12.x/docs/guides/troubleshooting.mdx
The ["Troubleshooting" guide](https://callstack.github.io/react-native-testing-library/docs/guides/troubleshooting#matching-react-native-react--react-test-renderer-versions) refers to the deprecated Expo command (`expo upgrade`).
This PR updates the verbiage about recommended versions and removes the outdated command with `npx expo install --fix`, which does both (check for recommended versions and dependency incompatibility with the Expo SDK version).
Here's a preview of the changes:
=> docs: Update outdated Expo command in Troubleshooting guide

src/helpers/accessibility.ts, src/matchers/__tests__/to-be-checked.test.tsx, src/matchers/to-be-checked.tsx, src/queries/__tests__/accessibility-state.test.tsx, src/queries/__tests__/role.test.tsx, website/docs/12.x/docs/api/jest-matchers.mdx, website/docs/12.x/docs/migration/jest-matchers.mdx
Resolves #1656 
The initial trigger for this PR has been consideration whether `toBeChecked` should support `Switch` control. After extensive research I concluded that this indeed should happen:
1. Jest DOM has concept of implict roles based on element type: https://github.com/testing-library/jest-dom/blob/4723de3664d129dfa97a877a4e0a9d171bc4c720/src/to-be-checked.js#L30
2. React Native's [Switch component](https://github.com/facebook/react-native/blob/5bbf5a4878fd3bab7b70f91e049bb6b986fd183b/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/views/switchview/ReactSwitch.kt#L24) and Android [`CompoundButton` view](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/widget/CompoundButton.java) (ancestor of RN `Switch`) natively has …
=> feat: support Switch checked state

src/cleanup.ts, src/fire-event.ts, src/helpers/matchers/match-label-text.ts, src/helpers/text-input.ts, src/native-state.ts, src/render.tsx, src/user-event/paste.ts, src/user-event/scroll/__tests__/scroll-to.test.tsx, src/user-event/scroll/scroll-to.ts, src/user-event/type/type.ts, website/docs/12.x/docs/api/events/user-event.mdx
Remove unnecessary `nativeState` optionality and cleanup.
=> refactor: simplify native state management

src/__tests__/config.test.ts, src/__tests__/host-component-names.test.tsx, src/__tests__/react-native-api.test.tsx, src/config.ts, src/helpers/accessibility.ts, src/helpers/format-default.ts, src/helpers/host-component-names.tsx, src/matchers/__tests__/to-have-accessible-name.test.tsx, src/queries/__tests__/hint-text.test.tsx, src/queries/__tests__/label-text.test.tsx, src/queries/__tests__/role-value.test.tsx, src/queries/__tests__/role.test.tsx, src/queries/hint-text.ts, src/queries/role.ts
Modifies existing a11y queries and matchers to support `Image` element with `alt` prop as a source for a11y label/accessible name.
Code that changes for `Image` + `alt` prop:
* `computeAriaLabel`
* `*ByLabelText` queries
* `*ByRole` queries
* `toHaveAccessibleName` matcher
Additionally:
* host `Image` element is not considered to have image role, as experimentally only Android screen reader announces it, while on iOS "image" trait is not given by default and requires explicit `role`/`accessibilityRole` to be set.
* added code to support mapping from `image` (AccessibilityRole` to `img` (ARIA `Role`), so that users can use both names to match image elements.
Complements/Replaces #1663 as now `getByRole('image', { name: 'alt text' })` or `getByLabelText` can be used to query images with …
=> feat: support `Image` with `alt` prop as label

src/fire-event.ts, src/matchers/types.ts, src/queries/__tests__/display-value.test.tsx, src/user-event/__tests__/clear.test.tsx, src/user-event/__tests__/paste.test.tsx, src/user-event/clear.ts, src/user-event/paste.ts, src/user-event/setup/setup.ts, src/user-event/type/__tests__/type.test.tsx, src/user-event/type/type.ts
Use TextInput native state value across the queries and matchers.
=> fix: use native state across the queries and matchers

README.md, extend-expect.d.ts, extend-expect.js, jest-setup.ts, matchers.d.ts, matchers.js, package.json, src/index.ts, src/matchers/__tests__/to-be-checked.test.tsx, src/matchers/__tests__/to-be-partially-checked.test.tsx
Extend Jest matchers by default when importing anything from `@testing-library/react-native`.
=> feat: automatically extend matchers

README.md
Corrects only the imports in the documentation example. The example mentions and uses `userEvent` but `fireEvent` is currently imported (which is not used in the example at all).
I guess, no need to.
=> docs: readme example userevent import

.github/workflows/ci.yml, jest-setup.ts, package.json, src/__tests__/config.test.ts, src/__tests__/render.test.tsx, src/config.ts, src/render.tsx, website/docs/12.x/docs/api/misc/config.mdx, website/docs/12.x/docs/api/render.mdx
Add `concurrentRendering` option to both `render` and `configure` that allows enabling concurrent rendering in the underlying React Test Renderer. The option is disabled by default not to break user tests but should be enabled in the next major release.
=> feat: option for enabling concurrent rendering

examples/basic/.eslintignore, examples/basic/components/AnimatedView.tsx, examples/basic/components/__tests__/AnimatedView.test.tsx, examples/basic/jest-setup.ts, examples/basic/package.json, examples/basic/yarn.lock, examples/cookbook/jest-setup.ts, examples/cookbook/package.json, examples/cookbook/yarn.lock
=> chore: update RNTL in example apps

.github/workflows/ci.yml, jest-setup.ts, src/__tests__/config.test.ts, src/config.ts, src/render.tsx
=> feat(v13): enable concurrent rendering by default

experiments-app/src/experiments.ts, experiments-app/src/screens/PressEvents.tsx, experiments-app/src/utils/helpers.ts, src/__tests__/render.test.tsx, src/fire-event.ts, src/helpers/component-tree.ts, src/user-event/press/__tests__/__snapshots__/longPress.test.tsx.snap, src/user-event/press/__tests__/__snapshots__/press.test.tsx.snap, src/user-event/press/__tests__/longPress.real-timers.test.tsx, src/user-event/press/__tests__/longPress.test.tsx, src/user-event/press/__tests__/press.real-timers.test.tsx, src/user-event/press/__tests__/press.test.tsx, src/user-event/press/constants.ts, src/user-event/press/press.ts, src/user-event/utils/dispatch-event.ts
Resolves: #1687 
Reverses `pressOut` and `press` event order so that it matches experimental data for regular presses:
1. `pressIn`,
2. (press duration)
3. `pressOut`
4. (no waiting) `press`. 
The previous setup matched edge case for very short (< 130ms) presses, when order was:
1. `pressIn`
2. (short press duration < 130 ms)
3. `press`
4. (wait till 130 ms - short press duration)
5. `pressOut`
See experiments: https://github.com/callstack/react-native-testing-library/wiki/Press-Events
All tests pass
=> fix: press event order

src/user-event/type/__tests__/type-managed.test.tsx, src/user-event/type/__tests__/type.test.tsx, src/user-event/type/type.ts, website/docs/12.x/docs/api/events/user-event.mdx, website/docs/13.x-next/docs/api/events/user-event.mdx
Resolves: https://github.com/callstack/react-native-testing-library/issues/1677
All tests pass
=> feat: add skip blur option

package.json, src/__tests__/render-debug.test.tsx, src/helpers/debug.ts, src/helpers/logger.ts, src/queries/__tests__/label-text.test.tsx, src/queries/make-queries.ts, src/render.tsx, yarn.lock
Use own logger, as `console.log` etc logged very verbose messages which included stacktrace, etc.
Before:
After:
Manually test logger output on sample inputs like, strings, arrays, objects, etc.
=> chore: better logger

src/render-hook.tsx, website/docs/13.x-next/docs/api/misc/render-hook.mdx, website/docs/13.x-next/docs/api/render.mdx
Expose `concurrentRoot` option on `renderHook`
=> fix: expose concurrent root in render hook

src/user-event/press/__tests__/press.real-timers.test.tsx
=> chore: workaround for User Event `press` race condition in tests

.github/workflows/ci.yml, .github/workflows/website.yml
Move test website job from `ci` to `website` workflow
=> refactor: cleanup website ci jobs

src/queries/__tests__/find-by.test.tsx, src/queries/make-queries.ts
- Updated the outdated ESLint plugin link in the `screen.isDetached` warning message.
- To ensure developers are directed to the correct documentation for `eslint-plugin-testing-library`.
=> fix: update ESLint plugin documentation link in warning message

src/__tests__/fire-event.test.tsx, src/helpers/pointer-events.ts
This allows users to test components that use `pointerEvents` in styles instead of props. Required for https://github.com/react-navigation/react-navigation/pull/12693
Related tests were copied and modified so`pointerEvents` is specified in `style` instead of props.
=> fix: check for `pointerEvents` in both props and styles

src/helpers/__tests__/accessiblity.test.tsx, src/helpers/accessibility.ts
Resolves #1801 by ensuring `Text` components with the `disabled` prop are correctly identified as disabled by `computeAriaDisabled`.
Previously, `computeAriaDisabled` didn't check for the `disabled` prop on `Text` elements, causing queries like `getByRole('text', { disabled: true })` to fail. The change adds a check to return `true` when `isHostText(element)` and `props.disabled` are both true, aligning `react-native-testing-library`'s behavior with expected accessibility states.
New unit tests have been added for `computeAriaDisabled` to verify this change. These tests cover:
1.  **`Text` component with `disabled={true}`:** Asserts `computeAriaDisabled` returns `true`.
2.  **`Text` component without `disabled` prop or `disabled={false}`:** Asserts `computeAriaDisabled` returns `false`. …
=> fix: toBeDisabled now also evaluates disabled prop when element is Text

website/docs/13.x/docs/api/events/fire-event.mdx, website/docs/13.x/docs/api/events/user-event.mdx, website/docs/13.x/docs/api/misc/render-hook.mdx, website/docs/13.x/docs/api/render.mdx, website/docs/13.x/docs/api/screen.mdx, website/docs/13.x/docs/guides/_meta.json, website/docs/13.x/docs/guides/react-19.mdx
=> docs: *Async docs

.github/actions/setup-deps-rn-latest/action.yml, .github/actions/setup-deps-rn-next/action.yml, .github/workflows/ci.yml, .github/workflows/react-native-latest.yml, .github/workflows/react-native-next.yml
Automatic nightly validation for `react-native@latest` in order to detect issues early.
Also:
- refactor other nightly jobs to match the same pattern
=> chore: react native nightly latest

.github/actions/setup-deps-react-18/action.yml, .github/workflows/ci.yml, src/__tests__/render-hook-async.test.tsx, src/__tests__/render-hook.test.tsx, src/__tests__/suspense-fake-timers.test.tsx, src/__tests__/suspense.test.tsx, src/render-hook.tsx, src/types.ts
=> fix: fix render hook typing

src/render-hook.tsx
Unsure when this happened, but noticed it when bumping a react-native project to 0.80.1. (Using typescript 5.5.4)
`renderHook` and `renderHookAsync` should not infer `Props` from `RenderHookOptions`.
See the following example:
```ts
type ExampleProps = {
required: string;
optional?: number;
};
const exampleHook = (_: ExampleProps) => {};
const { rerender } = renderHook(exampleHook, {
initialProps: {
required: '',
unknown: 1,
},
});
rerender({
required: '',
unknown: 1, // This should be invalid
optional: 1, // <--- type error here despite optional being a valid prop
});
```
This is resulting in optional props not specified in the initialProps setting to type-error when using `rerender()`.
This is because the `Props` generic type is being inferred from both `ExampleProps` and  `{ required: …
=> fix: Do not infer generic Props type from RenderHookOptions

src/matchers/__tests__/to-have-style.test.tsx, src/matchers/to-have-style.ts
=> fix: improve error message in toHaveStyles

src/__tests__/react-native-api.test.tsx, src/test-utils/json.ts
Fixes: https://github.com/callstack/react-native-testing-library/actions/runs/17284044745
=> chore: fix nightly test by excluding RCTSwitch style from snapshot
