babel.config.js
package.json
src/__tests__/render.test.js
src/index.js
yarn.lock

Fixes https://github.com/callstack/react-native-testing-library/issues/3

Add basic tests for render

---

README.md

Noticed a couple of typos while reading through the readme.
N/A

chore: fix typos in readme

---

src/waitForElement.js

Remove unnecessary flow expression that caused error in projects created by `expo-cli`.

Fix Remove unnecessary flow expression

---

README.md

Remove reference to instance in readme

---

package.json
yarn.lock

chore: update conventional-changelog-cli to version 2.0.11

---

package.json
yarn.lock

chore(package): update react-native to version 0.57.7

---

README.md

Fix link for api docs in read me file

---

README.md

Reverts callstack/react-native-testing-library#93

Revert "Fix link for api docs in read me file"

---

README.md

docs: Add note for `cleanup` being unnecessary

---

package.json
yarn.lock

Greenkeeper/eslint 5.14.1

---

LICENSE

update license to add rally
n/a

add rally to license

---

README.md

Fix small logo in README.md

---

docs/API.md
docs/Queries.md
website/i18n/en.json
website/sidebars.json

Adds new "Queries" section inspired by https://testing-library.com/docs/dom-testing-library/api-queries
Reading carefully

docs: add and update queries documentation

---

package.json
yarn.lock

chore: upgrade react-native to 0.59.8

---

package.json
yarn.lock

Greenkeeper/release it 12.1.0

---

package.json
yarn.lock

Upgrade `flow-copy-source` to `2.0.6`
Tests passing

chore: flow copy source 2.0.6

---

README.md

docs: install react-test-renderer typings

---

package.json
yarn.lock

chore: update @typescript eslint/eslint plugin to 1.10.2

---

docs/API.md

Adding `...queries` as a separate header for discoverability, updated description as well.
Nope

chore(docs): improve render and queries description

---

.flowconfig

Let's try to fix this flow issues on CI.
Flow passing 10/10 on CI.

chore: fix inconsistent flow fails on CI

---

docs/GettingStarted.md

This sentence was not very clear. Also, the word 'stand' was used, but I think the word 'understand' was what was intended.
The sentence has been updated to convey what I think was the intended meaning.

Fix unclear sentence and misuse of word 'stand'

---

package.json
website/yarn.lock
yarn.lock

Regenerating lock files to remove vulnerability warnings
Check website (edit: works)

chore: regenerate lock files to remove vulnerability warnings

---

docs/GettingStarted.md

Pointing to GitHub instead of 404.
Works on my end

docs: fix a link to example

---

package.json

Include links to the repository and the homepage

Include links to the repository and the homepage

---

package.json
yarn.lock

Bumping all Jest-related dev deps and deps (`pretty-format` is also a Jest dep), so we're on the latest. 
CI

chore: upgrade Jest deps to 26

---

README.md
website/docs/GettingStarted.md

Seems like it may mislead people. Fixes #361 
@alexakasanjeev is this clear enough now?

docs: clarify configuration to not omit preset react-native

---

website/docs/MigrationV2.md

clarify `UNSAFE_` functions are not scheduled for removal - just to avoid any confusion

clarify `UNSAFE_` functions are not scheduled for removal

---

flow-typed/npm/jest_v26.x.x.js
src/__tests__/jest-native.test.js

Flow typings for Jest are now compatible with version we use, let's upgrade.
CI

chore: bump Jest typings

---

website/docs/MigrationV2.md

I noticed was a typo in the migration to V2 documentation, this PR fixes it.

Fix typo in migration doc

---

README.md

Use the updated link for `react-testing-library` in the appreciation section, now that it moved to an org.
Confirm manually that you think I've provided the new canonical link on GitHub. Thanks!

Fix link for react-testing-library

---

yarn.lock

Upgrading logkitty through upgrading RN CLI.
CI

chore: bump logkitty to avoid security warnings

---

README.md

Hi I've added a blog post that I wrote about testing with the library. Same goes to my examples repo, that became very popular lately.

Update README.md - links to external resources

---

website/sidebars.js

Added migration guide v7 to website sidebar.

fix: added migration guide v7 to website sidebar

---

website/docs/MigrationV7.md

"is" should be replaced with "are" as it is plural referring to multiple nouns

Minor typo fix

---

README.md

This is a [youtube tutorial](https://youtu.be/CpTQb0XWlRc) on a simple setup and usage for React Native Testing Library & Jest Native

Add new link to External Resources in README.md

---

typings/index.d.ts

Fix the type bug for queryAllByTestId

---

website/docs/API.md

Small updates to the text and rendered output
None

docs: adjust wording around `debug`

---

yarn.lock

Bumping all deps related to Jest at once
CI

chore: bump jest to 26.3

---

website/docusaurus.config.js
website/package.json
website/yarn.lock

It works with minimal changes. Algolia search got a UX upgrade.
`cd website && yarn start`. Works on my end

chore(docs): bump docusaurus to alpha.61

---

website/docs/API.md

update API docs to no longer use `getByType` as it is deprecated and will be removed. Replaces the example to use `getByTestId`

docs: update scroll event api for flat list

---

website/docs/ReactNavigation.md

docs: Minor grammatical change

---

README.md

The jest.config file extention should be ".json" instead of  ".js"

:books: fix typo in README.md

---

website/src/css/index.module.css
website/src/pages/index.js

Adds Callstack notice to the website home page. Fixes some mobile layout issues btw.

docs: add Callstack notice

---

website/docs/GettingStarted.md

Fix the QuestionsBoard example to correct url

Fix QuestionsBoard example url

---

README.md
website/docs/MigrationV11.md
website/sidebars.js

Migration guide for version 11.
All checks and test pass.

docs: v11 migration guide

---

.circleci/config.yml
.github/workflows/example-apps.yml

Disable running test examples on merge to main. Manually run examples as a GH action.

chore: disable test examples workflow on main merge, add GH action for test examples

---

website/docs/Troubleshooting.md

Small update to troubleshooting doc.

chore: update troubleshooting guide with typical error messages

---

website/docs/MigrationV11.md

Changed targes in line 44 to targets.

docs: Changed targes in line 44 to targets.

---

examples/basic/package.json
package.json
yarn.lock

Update `@testing-library/jest-native`.

chore: update jest-native deps

---

README.md

Add codecov badge to README to show current coverage.

chore: add codecov badge to README

---

README.md

Fixes incorrect display of codecov badge

fix: cleanup codecov badge links

---

website/docs/API.md

Rewrite waitFor documentation to be more complete. Explains further in details the internal behavior of waitFor and some of its pitfalls. Also add a section on how it works when using fake timers. I added as well a link to the readme for the part regarding the custom jest preset but I wonder if this should be in the docs as well rather than only in the readme.
@mdjastrzebski @AugustinLF @MattAgn wdyt ?

docs: rewrite documentation on waitFor

---

package.json
renovate.json

chore: renovate config

---

website/package.json
website/yarn.lock

Upgrade Docusaurus & React versions.

chore: upgrade docusaurus 2.3.1

---

yarn.lock

`yarn upgrade`
All test should pass.

chore: yarn upgrade - 2023-03-06

---

yarn.lock

chore: upgrade deps 2023-03-16

---

renovate.json

chore: disabled renovate

---

yarn.lock

chore: update deps 2023-04-04

---

package.json
yarn.lock

fix: remove incorrect dependencies

---

package.json
yarn.lock

Remove unused dep: `conventional-changelog-cli`.

chore: remove conventional-changelog-cli package

---

examples/basic/__tests__/App.test.tsx
examples/basic/package.json

Update example/basic with UserEvent code.
Example test should pass.

chore: update basic example with User Event

---

examples/basic/__tests__/App.test.tsx
examples/basic/package.json

Apply UserEvent `clear` to examples/basic.

chore: apply UserEvent clear to examples/basic

---

website/docs/API.md
website/docs/GettingStarted.md
website/docs/MigrationV11.md
website/docs/MigrationV12.md
website/docs/MigrationV2.md
website/docs/MigrationV7.md
website/docs/MigrationV9.md
website/docs/Queries.md
website/docs/ReactNavigation.md
website/docs/ReduxIntegration.md
website/docs/TestingEnvironment.md
website/docs/Troubleshooting.md
website/docs/UnderstandingAct.md
website/docs/UserEvent.md
website/docusaurus.config.js

Replace manually (or vscode plugin-generated) TOCs with docusaurus generated ones.
Check website, focus on TOCs.

docs: setup automatic table of contents

---

.github/workflows/example-apps.yml
website/docker/Dockerfile

[Node 16 is dead](https://nodejs.org/en/blog/announcements/nodejs16-eol) and we need to upgrade for support and security (OpenSSL is no longer supported).
CI

Upgrade Node for security

---

package.json
yarn.lock

chore: restore latest types for react-test-renderer

---

package.json
pure.d.ts

Same as https://github.com/testing-library/react-testing-library/pull/696
Fixes missing typedefs for pure.
Tested with a patch-package in another app.

Adds typedefs for pure

---

extend-expect.d.ts
extend-expect.js
package.json

chore: expose Jest Native exports

---

website/docs/UserEvent.md

docs: remove beta status for User Event

---

CONTRIBUTING.md
website/docs/API.md
website/docs/TestingEnvironment.md
website/docs/UserEvent.md

Proofreading and improving text style.

docs: updates to docs

---

website/docusaurus.config.js
website/package.json
website/src/css/custom.css
website/yarn.lock

chore: upgrade docusaurus

---

examples/basic/package.json
examples/basic/yarn.lock

chore: upgrade basic example to expo 50

---

README.md

Fix broken link into README
Open the link

fix: Rally Health link into readme

---

.vscode/settings.json
src/fire-event.ts
src/helpers/__tests__/accessiblity.test.tsx
src/helpers/accessibility.ts
src/helpers/find-all.ts
src/helpers/matchers/match-accessibility-state.ts
src/helpers/matchers/match-accessibility-value.ts
src/helpers/matchers/match-label-text.ts
src/matchers/to-be-busy.tsx
src/matchers/to-be-checked.tsx
src/matchers/to-be-collapsed.tsx
src/matchers/to-be-expanded.tsx
src/matchers/to-be-partially-checked.tsx
src/matchers/to-be-selected.ts
src/matchers/to-be-visible.tsx
src/matchers/to-have-accessibility-value.tsx
src/matchers/to-have-accessible-name.tsx
src/pure.ts
src/queries/accessibility-state.ts
src/queries/accessibility-value.ts
src/queries/role.ts
src/types.ts

Resolves (in non-breaking way) #1490 
All tests should pass.
Manual intellisense testing with VS Code

feat: by role ts hints

---

.github/workflows/ci.yml
README.md

chore: rename ci workflow

---

package.json
yarn.lock

chore: upgrade RN to 0.75

---

package.json
yarn.lock

chore: update deps 2024-10-31

---

.github/workflows/ci.yml

chore: provide codecov token

---

examples/basic/package.json
examples/basic/yarn.lock
examples/cookbook/package.json
examples/cookbook/yarn.lock

chore: update examples 2024-12-08

---

package.json
src/index.ts

Move RNGH from deps to dev-deps

fix: RNGH dep

---

src/index.ts

feat: ensure proper `react-test-renderer` version

---

README.md

We're adding new banners to Callstack repos :)

docs: new banner
